### ISSUE TITLE
mip-bind的class只会叠加，但是现在需要动态删除

### ISSUE THREAD

**Issue by JasonDurian** [mipengine/mip-extensions#1000]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
最近mip组件的修改当中让class不会被覆盖了，但是请问一下如果我想动态的删除一个class该怎么做？

## 您的建议方案
例如：
![image](https://user-images.githubusercontent.com/24243477/34904304-3438354e-f87e-11e7-99f7-fe75c72fe0ad.png)
为active的class需要在两个按钮之间切换，现在只要点击过的按钮，那么加上去的active就一直存在了。

**Comment by xuexb** [comment]
> 最近mip组件的修改当中让class不会被覆盖了

👍

**Comment by JasonDurian** [comment]
建议可以在传入的class为空或者false等的时候，删除所有存入的class

**Comment by JasonDurian** [comment]
用object或者array也有一些问题

**Comment by xuexb** [comment]
召唤 @wupengFEX

**Comment by wupengFEX** [comment]
现在有两种方案：
一：保持目前现状，class只classList.add增加，但是不能删除；
二：恢复原有逻辑，但是如果需要覆盖就得自己拼接好字符串，比如原 class 为 a b，现在如果需要变化则通过 MIP.setData({cls:"a b c"}) 或 MIP.setData({cls:"a"}) 这种形式 @JasonDurian @xuexb 二位觉得如何？

**Comment by xuexb** [comment]
二的话就会遇到：本身 `body` 就有样式

```html
<body class="a" m-bind:class="data">
```

这个 `data` 会直接覆盖，使用者必须明确知晓这个事，但确实比较坑。

**Comment by JasonDurian** [comment]
对的 如果用了m-bind:class="xxx"的话 原来的标签就不能有class了
