### ISSUE TITLE
mip-form使用请教

### ISSUE THREAD

**Issue by nordon-wang** [mipengine/mip-extensions#1002]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
在使用mip-form时，遇到一个需求是，在表单提交成功之后清空表单内容，请问应该如何做。现在是不知道如何获取到表单提交成功时的状态返回。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
若是能增加一个属性来控制表单提交成功后是否清空表单最好啦·····

**Comment by schoeu** [comment]
你好，请描述一下需要用到提交表单清空表单的场景。 谢谢

**Comment by nordon-wang** [comment]
@schoeu  需求是：当表单提交通过校验之后，便清空表单内容，若是提交没有通过校验，则不清楚表单。

**Comment by nordon-wang** [comment]
@schoeu 还有一个疑问就是，使用mop-form时，可以自己手动接收返回的状态吗？

**Comment by lrvingyang** [comment]
mip-form 打开微信分享页面mip-form显示不正常！ 无法控制input宽度

**Comment by wupengFEX** [comment]
@nordon-wang 目前组件是没有提交清空的功能。如果是异步

**Comment by wupengFEX** [comment]
@nordon-wang 
- 目前组件是不支持提交清空的功能；
- 如果是异步提交表单（即在当前页面通过 ajax 请求），状态是由组件内处理的，开发者不需关心，同时也不能获取到；

@lrvingyang 问题已关联至 #1009，请通过 #1009 关注问题状态。
