### ISSUE TITLE
使用mip-bind绑定a herf属性，不能通过mip校验

### ISSUE THREAD

**Issue by fuufuuf** [mipengine/mip-extensions#1022]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [x] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
页面使用mip-bind组件绑定href属性，使用校验工具，报错
58行,5列:标签 'a' 的强制性属性 'href' 缺失( 错误代码:06200501)
72行,5列:标签 'a' 的强制性属性 'href' 缺失( 错误代码:06200501)

页面url
http://xmlyfm.zjzhidao.cn/mip/xmly.html?baidu_sem={keywordid}_{keyword}_{creative}

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：http://xmlyfm.zjzhidao.cn/mip/xmly.html?baidu_sem={keywordid}_{keyword}_{creative}
5. 复现操作：
使用https://www.mipengine.org/validator/preview
填写url - http://xmlyfm.zjzhidao.cn/mip/xmly.html?baidu_sem={keywordid}_{keyword}_{creative}

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by wupengFEX** [comment]
@fuufuuf 
a 标签默认必须有 href，如果使用 bind 动态绑定的话，可以默认指定一个路径，如：
`<a href="默认地址" m-bind:href="url">`

**Comment by fuufuuf** [comment]
我加了一个默认标签，通过了。问一下，如果校验失败，是不是就肯定不会被百度mip收录

**Comment by wupengFEX** [comment]
校验关联的是页面最终打开效果，不通过校验的页面，网络库中可能会有，但是打开方式就不是 mip 的形式了，同时不会走 cache 页面逻辑，满足校验才能拥有最佳用户体验。
