### ISSUE TITLE
建议像mip-showmore这样会动态计算属性的组件追加rem等其他单位的支持

### ISSUE THREAD

**Issue by mulianju** [mipengine/mip-extensions#1028]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 复现方式（线上bug 填写此项）
1. 手机型号：all
2. 系统版本：all
3. 浏览器及版本：all
4. 页面URL：all
5. 复现操作：无

## 需求描述（新需求 填写此项）
1. 效果页面URL： 无
2. 效果描述:  无

## 您的建议方案
建议像mip-showmore这样会动态计算属性的组件追加rem等其他单位的支持

**Comment by momofan** [comment]
@mulianju 需求合理，可以直接贡献代码 @wupengFEX 关注

**Comment by wupengFEX** [comment]
@mulianju 组件内部一般都是取最终渲染样式，和使用什么单位没有太大关系。具体哪里使用 rem 会有问题呢？mip-showmore 内部使用 rem 元素也同样可以解析成功，请提供下具体案例，如线上出现问题的 URL，方便看具体问题，感谢！
