### ISSUE TITLE
mip-sidebar 组件打开状态再open就关闭不了

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#1045]
- 复现链接：<https://m.baidu.com/mip/c/mip.256.cc/dianying/10-all-all-all-year.html>
- 代码逻辑问题：

<https://github.com/mipengine/mip-extensions/blob/6475b01540f93347eb278a7c40c7f585c947bb29/src/mip-sidebar/mip-sidebar.js#L26-L34>

**Comment by tayqassqan** [comment]
4.18已上线修复此问题。
