### ISSUE TITLE
关于mip-bind的一个小建议，也许是bug

### ISSUE THREAD

**Issue by vivine** [mipengine/mip-extensions#1055]
https://github.com/mipengine/mip-extensions/blob/b2cefde0fc67bcbfadc6c665392d48db64cd0b1f/src/mip-bind/mip-compile.js#L147-L153

此处应该增加一个判断：`newVal` 为空，或者为 `false` `0` 之类的，应该不执行 `setAttribute`，或者要移除该属性。

场景：当一个input需要disabled的时候，满足条件后加上了这个属性，但条件不满足的话就没法去掉了。这样就一直不可点击。

希望尽快解决一下啦~~~谢谢~~~

**Comment by vivine** [comment]
补充一点，应该对所有的 `boolean attribute` （布尔值的属性，如：`checked` `selected` `readonly` 等）都做一下处理，当 `newVal` 为空的时候，移除该属性，要不然没办法再变回来了。

**Comment by vivine** [comment]
再补充一点
当我用 `m-bind` 给一个` input` 绑定属性 `value` 的时候，如：`<input type="text" m-bind:value="xxx">` 当`xxx` 发生变化的时候
1、`value` 值是会跟着变化的
2、当我给 `input` 额外绑定 `change` 事件（这样绑定：`input.addEventListener('blur', function () { })`），却监听不到这个 `change`

猜想：可能改变 `value` 是通过 `setAttribute` 来设置的，并不是通过 `input.value = xxx` 这样来设置，所以监听不到

望官方给个解决方案！！！

**Comment by wupengFEX** [comment]
@vivine 很棒的建议！m-bind 属性绑定功能本周会添加空值删除的功能。input 类数据监听目前不支持，该功能也会尽快制定方案集成到 bind 功能中。

**Comment by vivine** [comment]
@wupengFEX

关于 input 的 change 事件，我的使用场景是：用 m-bind 来绑定 value 值，改变数据是在页面中来做的，然后我在组件里边要监听 input 的 change 来做别的一些事儿，不只是改变数据。

我昨天查了一下，input 的 change 事件触发条件：focus时获取旧的值，blur的时候判断值改变没有，改变就触发 change

而我的使用场景里，通过组件外面的东西来改变数据从而达到组件里边 input 的值改变，组件里边 input 并没有 focus 或者 blur，所以触发不了 change

解决办法：我猜只能在 mip-bind 里边，当给表单元素（如 input）设置属性的时候，手动触发一下 change 事件了。

```javascript
var canChangeDomTagArr = ['INPUT', 'SELECT'];
if (canChangeDomTagArr.indexOf(node.tagName) > -1) {
    node.change();
}
```

**Comment by xuexb** [comment]
hi @vivine ，你说的方案确认有使用场景，但我尝试了下，给表单元素（如 `input` 、`select`）绑定 `onchange` 事件，通过外部设置该元素的值时，方法如：

- mip-bind - `MIP.setData({});`
- Vue - `this.inputValue = 'new';`
- Zepto - `$('el').val('new');`
- DOM - `document.querySelector('input').value = 'new';`

都不会触发元素的 `onchange` 事件，针对你这个场景可以在你的组件中暴露一个事件，让页面中设置数据后再触发该事件，如：

```html
<input m-bind:value="name">
<mip-自定义组件 id="自定义"></mip-自定义组件>
<div on="tap:MIP.setData({name: 123}) tap:自定义.validate">
    点我修改哦~
</div>
```

**Comment by wupengFEX** [comment]
@vivine `m-bind` 绑定属性时，数据为空值则删除属性的功能已上线。

**Comment by vivine** [comment]
@wupengFEX 还有个小小的问题，就是比如说 `input type="radio"` 的 checked 属性，我通过js改变数据了，审查DOM的时候，checked属性已经加上，但是这个单选框就是补选中。

查了一下，咱们都是通过setAttribute来设置属性，但是对于 `boolean attribute` 好像不太好使，得用prop来者之，也就是：`input.checked=true` 或者 `input.checked=false` 才能起作用。不知道是不是这个原因

你们查看一下吧！！！谢谢

**Comment by xuexb** [comment]
hi @vivine ，感谢提出的问题和建议，我写了个示例看了下，针对 `prop` 值确实是需要设置属性才生效，如常用的：

```
checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped
```

而普通文本框的 `checked` 事件，在没有用户操作前，使用  `m-bind:checked` 是生效的，一旦用户操作了文本框元素，那么绑定的属性将不可用，需要使用属性方式才可以生效。

@wupengFEX 如果说这些属性只使用 `el.checked = val` 这可能导致有些场景覆盖不到，如：

```css
.el[selected] {}
```

如果没有设置 `attr` 而带来问题，这个选择器就不会生效，而代码层面又不会知道用户是想使用属性样式选择器还是使用属性来选中元素。

**Comment by xuexb** [comment]
示例链接：<https://xuexb.github.io/learn-mip/src/mip-bind/>

**Comment by vivine** [comment]
@xuexb 正如你所说，默认展示的时候 `m-bind:checked` 是生效的，但我对其进行操作后，数据改变了，checked属性在DOM里边页改变了，但也就是改了属性而已，而真正的 `input.checked` 并没有改变。

希望尽快解决一下吧，这两天好多操作都需要这个。

谢谢啦~~~~
