### ISSUE TITLE
mip-bind 在本地文件打开时报错

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#1061]
## 问题分类

- MIP 组件使用

## 问题描述

本地打开包含 `mip-bind` 的 HTML 文件时报错，如：

```
mip-bind.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').
```

对应源码：

<https://github.com/mipengine/mip-extensions/blob/8b1ec770aef50654a49fbaf88f9b7fac99cc7b47/src/mip-bind/mip-data.js#L60-L68>

**Comment by wupengFEX** [comment]
> Lastly, posting a message to a page at a file: URL currently requires that the targetOrigin argument be "*". file:// cannot be used as a security restriction; this restriction may be modified in the future.

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) 上的介绍，同时我们开发时也是基于安全性考虑，所以才加上了域名限制，而 `file://` 下有一定要求和安全限制，如需要设置 `targetOrigin` 为 `*`。我认为从这些方面考虑，`file://` 就不要做特殊化，保持统一步调，但是需要在文档里面进行说明。 @xuexb 你觉得呢？

**Comment by tayqassqan** [comment]
出于安全策略考虑，我们讨论后决定不支持本地的file协议。
