### ISSUE TITLE
关于mip-data 不支持跨域发送 cookie 的问题

### ISSUE THREAD

**Issue by vivine** [mipengine/mip-extensions#1079]
https://github.com/mipengine/mip-extensions/blob/983f8b2af227a5a6227a8d1fb4608f4c21b7fb53/src/mip-bind/mip-data.js#L75-L92

mip-data 这个地方的跨域问题，服务端已经配置 cors 跨站访问，解决了数据能读到的问题。

**重点是：mip-data 这个地方用的fetch，并没有支持跨域发送 cookie，我的场景是在服务端要获取cookie来做一些事情。**

建议：在 mip-data 组件上加个属性，让用户来控制是否跨域发送 cookie。

以上！

**Comment by wupengFEX** [comment]
关联 #1076
