### ISSUE TITLE
mip-infinitescroll 超时参数错误

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#1083]
## 问题

- MIP 组件使用

## 问题描述

发现组件中取的超时参数有问题：

<https://github.com/mipengine/mip-extensions/blob/9914d20b1f346752761584f96a138f0a0b74de6a/src/mip-infinitescroll/mip-infinitescroll.js#L89-L94>

参数应该是 `self.params.timeout` ，导致超时参数配置无效，永远取的 fetch-jsonp 的默认5000

**Comment by tengxumin** [comment]
希望尽快解决一下这个，项目上线一直有个问题，谢谢~~~

**Comment by xuexb** [comment]
hi @tengxumin ，这是参数导致的配置（`<script type="application/json">`）内 `timeout` 参数没有生效， #1085 上线后配置就会生效，建议 @tengxumin 把网站内的参数配置成理想态，不然就会存在：

- 目前：配置内是 3000 ，生效是 5000
- 上线后：配置内是 3000 ，生效是 3000
