### ISSUE TITLE
mip-list 中使用 mip-bind 不生效

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#1114]
## 问题分类

- MIP 组件使用

## 问题描述

在 mip-list 组件内使用 mip-bind 绑定数据时，由于 mip-list 是动态插入到页面中，导致 mip-bind 扫描页面元素时没有绑定，见 Demo ：

<https://admin.static.xuexb.com/html/xuexb/test-bind-list.html>

**Comment by tayqassqan** [comment]
mip-list 迁移MIP 2.0解决

**Comment by zhuguoxi** [comment]
在mip2.0上解决

**Comment by MissQ7** [comment]
不能动态绑定src啊
