### ISSUE TITLE
关于http使用mip-pix 统计组件

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#1120]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ X] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [X ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
由于服务器配置原因，目前不考虑安装证书，kmgmy.com 未使用htpps协议，请问在不使用https证书情况下，如何实现统计呢？

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：http://kmgmy.com
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案

希望http网站不使用代理NDS代理服务，也可以实现统计MIP站点数据。

**Comment by tayqassqan** [comment]
如果希望在百度搜索中生效MIP，我们建议你使用https的服务。 @lrvingyang
