### ISSUE TITLE
多个组件的通用逻辑部分如何复用？

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1136]
## 使用场景：
- 【给后端发请求，将请求数据渲染到页面中】这个逻辑是mip-list, mip-infinitescroll，mip-custom(搜索合作广告)通用的逻辑
- 【元素的展开动画】，从高度固定动画展开为高度auto，需要经过一次auto实际高度的计算，再添加动画。这个逻辑也可以被mip-showmore, mip-accordion 等交互组件复用。

## 建议：
抽离维护通用组件依赖AMD模块，放到common文件夹中，在组件中使用`require`加载。

**Comment by tayqassqan** [comment]
> 【给后端发请求，将请求数据渲染到页面中】这个逻辑是mip-list, mip-infinitescroll，mip-custom(搜索合作广告)通用的逻辑
这个是指fetch + render吗？重复的代码也可以贴一下
> 【元素的展开动画】，从高度固定动画展开为高度auto，需要经过一次auto实际高度的计算，再添加动画。这个逻辑也可以被mip-showmore, mip-accordion 等交互组件复用。

这里也还不太清楚具体想做的，可以进一步使用伪代码解释一下

**Comment by jennyliang220** [comment]
mip-accordionhttps://github.com/mipengine/mip-extensions/blob/master/src/mip-accordion/mip-accordion.js#L149

**Comment by tayqassqan** [comment]
确认一下MIP 2.0中是否有模块管理和复用的机制

**Comment by VenyXiong** [comment]
这个机制在2.0默认支持了，1.0暂时不考虑新增机制支持
