### ISSUE TITLE
mip-showmore 折叠组件，如果内容高度仅大于折叠高度一点点（比如两行字），就不需要严格折叠了

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1144]
mip-showmore 折叠组件，如果内容高度仅大于折叠高度一点点（比如两行字），就不需要严格折叠了。不然用户点击【展开】后，新内容很少，体验并不好。

![16b8067c328103f060467340b0338c2e](https://user-images.githubusercontent.com/8498677/40218667-b10c24bc-5aa4-11e8-951e-61dd6b78c932.png)

**Comment by oott123** [comment]
改成两个属性：一个 `threshold`，控制在多少高度之内折叠；一个 `height`，控制折叠到多高。

**Comment by jennyliang220** [comment]
> 一个`threshold`
@oott123 其实直接加个`buffer`参数（单位：px）也可以是吧。省的开发者计算1.5屏折叠的`threshold`应该是多少

**Comment by oott123** [comment]
@jennyliang220 听起来都行。个人没偏好

**Comment by zhuguoxi** [comment]
https://github.com/mipengine/mip-extensions/commit/041e5dab5a339482d9d43288fda392f6b9815ca5
