### ISSUE TITLE
希望增加 组件样式作用域

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip-extensions#1150]
## 问题描述
- 问题：组件嵌套时，父组件会影响子组件样式。
- 影响：组件嵌套不好用，第三方组件编写时，业务逻辑更复杂、功能更单一、处理更trike，降低了组件的复用性、增加组件数量

**Comment by tayqassqan** [comment]
确认一下MIP 2.0是否解决此问题。

**Comment by jenkey2011** [comment]
确认，MIP 2.0 支持
