### ISSUE TITLE
新增组件，可以配置百度来源显示/不显示特定的元素，如站长自己的顶bar

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1154]
如下图，站点自己配置了返回按钮，头部内容，其实跟百度提供的bar有功能重复。建议增加mip-is-iniframe 组件，判断是否在mip-shell环境下（存在顶bar），隐藏/展示页面某部分内容。
1. 返回按钮重复
![image](https://user-images.githubusercontent.com/8498677/40340284-b64a3a86-5db0-11e8-84a7-0f0a4ce9e5f4.png)

2. 网站名重复
![0c6683146f287318180c50c0673e00a8](https://user-images.githubusercontent.com/8498677/40340403-5a2627c8-5db1-11e8-846d-136ab1cb3387.png)

**Comment by tayqassqan** [comment]
mip-shell进行此能力支持。

**Comment by jennyliang220** [comment]
需要提供使用文档

**Comment by tayqassqan** [comment]
我们也需要考虑没使用mip-shell的时候如何处理双bar问题

**Comment by VenyXiong** [comment]
这部分处理逻辑，由熊掌号业务逻辑考虑，暂时不继续跟进处理。
