### ISSUE TITLE
mip-bind 不支持同时改变多个数据（setData）

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1155]
官网[mip-bind 示例](https://www.mipengine.org/examples/mip-extensions/mip-bind.html#markdown-doc-%E5%85%B7%E4%BD%93%E6%93%8D%E4%BD%9C)中，setData只能同时改变一次数值。

![42c8a7bd389095d1dddc75172d8eac99](https://user-images.githubusercontent.com/8498677/40344850-45feca08-5dc9-11e8-8636-642abc1d4e5e.png)

遇到要同时改变data中多个数值，就只能这么写了

![1fb22420ce56ecffc16e79207734fb66](https://user-images.githubusercontent.com/8498677/40344854-4857fafe-5dc9-11e8-825d-03758e30c2a2.png)

但正常会这么写吧：

![576da14871f9f61e39be2020bf3df4b0](https://user-images.githubusercontent.com/8498677/40344920-978930e8-5dc9-11e8-9f06-e4344937be59.png)

可以run的示例：

```html
<mip-data>
    <script type="application/json">
      {
          "name1": "扫地僧",
          "age1": 25,
          "home1": "北京"
      }
    </script>
</mip-data>

<!--这样写竟然不能解析？setData的内容是多么标准的JSON-->
<button on="tap:MIP.setData({name1:'互联网从业者', home1: '上海'})">点我啊啊啊</button>

<!--必须要这么写才能够成功-->
<button on="tap:MIP.setData({name1:'互联网从业者'}) tap:MIP.setData({home1:'上海'})">点我啊啊啊</button>

<p>age1: <span m-text="age1"></span></p>
<p>name1: <span m-text="name1"></span></p>
<p>home1: <span m-text="home1"></span></p>
```

**Comment by wupengFEX** [comment]
`event-action` [正则解析](https://github.com/mipengine/mip/blob/master/src/utils/event-action.js#L13)的问题，`setData` 数据有空格解析错误，按正则看所有 `event-action` 都会有这个问题。

**Comment by tayqassqan** [comment]
#1069
