### ISSUE TITLE
mip-mustache组件的template 在渲染之前 在页面中生成一个 document-fragment; 但是table 会排除所有的字符串到table标签的前面，类似table中不能使用div的情况。 使用注释 {{}}，可以解决这个问题。但是再mip页面中自动过滤了我的注释。 请问还有更好的解决方案么，除了不用table。希望能看到，谢谢。

### ISSUE THREAD

**Issue by yt540951254** [mipengine/mip-extensions#1161]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by tayqassqan** [comment]
请提供更多示例，便于我们复现和追查问题。

**Comment by jennyliang220** [comment]
vue 中有类似的解决办法：
https://cn.vuejs.org/v2/guide/components.html#%E8%A7%A3%E6%9E%90-DOM-%E6%A8%A1%E6%9D%BF%E6%97%B6%E7%9A%84%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

![image](https://user-images.githubusercontent.com/8498677/41229025-09036ec6-6dad-11e8-8705-ae6f5e53b994.png)

**Comment by VenyXiong** [comment]
把 table 写进 template里。
