### ISSUE TITLE
mip-list组件优化

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1176]
现在的MIP列表组件，每个页面只能放一个列表，使用加载更多，放多个后，加载更多的文本只能默认替换第一个，建议能加多个。

![1](https://user-images.githubusercontent.com/8498677/41012636-14dc2d50-6975-11e8-90b6-d69c71ba5f63.png)

**Comment by alertsong** [comment]
希望尽快处理 #

**Comment by tayqassqan** [comment]
属于组件bug，需要修复选择方式。

**Comment by allen886** [comment]
美女厉害啊  我只知道有问题 但是不知道有什么问题

**Comment by alertsong** [comment]
都提了半年多了，还没修复呀

**Comment by zqcxxx** [comment]
已修复
