### ISSUE TITLE
mip页面的内部滚动方案导致浏览器不能获取到页面滚动事件，不能伸缩原生导航栏。

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#1188]
[IMG_9336.mp4.zip](https://github.com/mipengine/mip-extensions/files/2121852/IMG_9336.mp4.zip)
github 不能放mp4, zip了一下。

**Comment by tayqassqan** [comment]
由于MIP页面是通过iframe实现的，滚动事件无法很好控制（浏览器行为），所以暂时无解决方案。
