### ISSUE TITLE
mip-showmore组件展开更多按钮下方遮盖链接可以点击

### ISSUE THREAD

**Issue by DOBEEE** [mipengine/mip-extensions#1201]
## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
组件展开更多按钮下方遮盖链接可以点击，
原因有2，
1，展开更多按钮没有阻止冒泡，
2，渐变层距离展开更多按钮部分浏览器下会有1-2px的间隙，会导致误触下方的词。

## 复现方式（线上bug 填写此项）
1. 手机型号：iphone7
2. 系统版本：ios10
3. 浏览器及版本：手百
4. 页面URL：https://m.baidu.com/s?word=http://m.120ask.com/askg/mip_detail/29067785&sid=123970
5. 复现操作：点击展开更多会误触被覆盖的链接词

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
1.展开更多按钮加上阻止冒泡事件，
2.渐变层移-2px。

**Comment by tayqassqan** [comment]
需要核心代码一起讨论tap的实现，目前tap上有穿透bug

**Comment by zhuguoxi** [comment]
https://github.com/mipengine/mip-extensions/tree/master/src/mip-showmore#%E7%82%B9%E9%80%8F%E9%97%AE%E9%A2%98%E5%A4%84%E7%90%86
