### ISSUE TITLE
accordion 组件内第二个节点 在百度熊掌号中消失

### ISSUE THREAD

**Issue by lijinbao0325** [mipengine/mip-extensions#1202]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
accordion sessions-key="mip_2" 组件内第二个节点 在百度熊掌号中消失。正常mip页没问题。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：任意
3. 浏览器及版本：任意
4. 页面URL：
  普通MIP链接：m.gmz88.com/mip_xiazai/160814.html
  熊掌号链接： http://m.baidu.com/paw/c/m.gmz88.com/mip_xiazai/160814.html
5. 复现操作：
 pc直接浏览

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:
   恢复消失内容即可

**Comment by jenkey2011** [comment]
第二个节点中，弹框使用了fixed，节点被清空了。
如果使用fiexed布局，请使用`mip-fixed`组件

**Comment by lijinbao0325** [comment]
thank you
