### ISSUE TITLE
mip注册自定义事件被触发时，透传的event对象有兼容问题

### ISSUE THREAD

**Issue by jenkey2011** [mipengine/mip-extensions#1203]
背景：上周收到一个问题，ios触发自定义事件报错
问题原因：触发自定义事件时，通过`event.path.id`值判断下一步操作。IOS透传`event`中，没有`path`属性

<img width="563" alt="70f840f0d371fd51190314a819ae82a3" src="https://user-images.githubusercontent.com/20010737/41847439-8b688716-78ac-11e8-875f-24771c8083c8.png">
---
<img width="829" alt="faee67580ba2e566bbc41d09132eacf6" src="https://user-images.githubusercontent.com/20010737/41847250-f0e03342-78ab-11e8-9097-908552d71ddb.png">

**Comment by tayqassqan** [comment]
path不是标准的属性，这个属于浏览器兼容问题，不推荐使用。
