### ISSUE TITLE
mip-form组件，https post方式，IOS苹果手机 Serevr无法获取表单数据

### ISSUE THREAD

**Issue by roadingon** [mipengine/mip-extensions#1207]
## 问题分类
（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [x ] MIP 页面内容（广告不显示，排版错乱）
- [x ] MIP 页面不通过校验
- [x ] MIP-Cache下效果异常

## 问题描述
mip-form组件，post方式，Serevr无法获取表单数据

## 复现方式（线上bug 填写此项）
1. 手机型号：苹果7plush
2. 系统版本：IOS 10.3.3
3. 浏览器及版本：微信
4. 页面URL：http://m.3490.cn/exh/503/mess.html#msg（页面已改为get方式代替）

## 您的建议方案
自己和百度mip组件哥已测，暂时定位为IOS版本问题，详情未知，需跟进。

**Comment by Espoir-L** [comment]
建议先使用原生form重新试一下，看看是否与mip-form组件的问题。以方便我们定位问题。
