### ISSUE TITLE
mip2 mip-list 被嵌套遍历了2次list

### ISSUE THREAD

**Issue by qianduan7** [mipengine/mip-extensions#1209]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
自定义MIP组件，嵌套了mip-list组件 遍历了2次数据

```
<mip-wrapper>
    <p>使用MIP-LIST 为什么会出现2次？</p>
    <mip-list synchronous-data>
        <script type="application/json">
            {
                "items": [
                    {
                        "name": "1"
                    },{
                        "name": "2"
                    }
                ]
            }
        </script>
        <template type="mip-mustache">
            <div>{{name}}</div>
        </template>
    </mip-list>
</mip-wrapper>
```

```
<template>
    <div class="app">
            <slot></slot>
    </div>
< /template>
```

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by Espoir-L** [comment]
辛苦辉泉排查下该issue。 @huanghuiquan

**Comment by VenyXiong** [comment]
mip2线上已修复~
