### ISSUE TITLE
关于validateelement检查后提示`define`必须使用匿名模块定义的问题

### ISSUE THREAD

**Issue by zjtt** [mipengine/mip-extensions#1211]
![Uploading image.png…]()
![_20180712111714](https://user-images.githubusercontent.com/22001904/42610815-cba1ef0e-85c5-11e8-9439-2c0e6c5893b2.png)
我传递的就是匿名函数为什么提示不是匿名的？

**Comment by zqcxxx** [comment]
可以描述的更清楚点嘛？目前给出的信息很难帮你定位
