### ISSUE TITLE
form表单,checkbox的校验请教

### ISSUE THREAD

**Issue by nordon-wang** [mipengine/mip-extensions#1213]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [x ] MIP 页面内容（广告不显示，排版错乱）
- [x ] MIP 页面不通过校验
- [x ] MIP-Cache下效果异常

## 问题描述
一组复选框，<input type="checkbox" name="names[]">，想对这个复选框进行必选校验，该如何做？

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
若是能满足这种需求，请给出demo示例提供参考

**Comment by Espoir-L** [comment]
该功能后期考虑在mip2的mip-form中实现相关功能，详细的内容可以查看，mip2的相关issue：https://github.com/mipengine/mip2-extensions/issues/225
