### ISSUE TITLE
mip-lightbox 弹出层组件在打开与关闭时增加相应的事件处理

### ISSUE THREAD

**Issue by ClimbYU** [mipengine/mip-extensions#1214]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-lightbox 弹出层组件在打开与关闭时没有相应的事件处理，导致无法在弹层打开或关闭时做相应业务逻辑处理

## 您的建议方案
增加弹出层打开或关闭时的事件处理，能够在打开或关闭时做相应逻辑处理

**Comment by VenyXiong** [comment]
这里建议自己实现对应的弹出组件逻辑，这个部分设计会在mip2.0的组件中做相关实现
