### ISSUE TITLE
在写mip-custom的模板时候，debug信息不完善，不便于追查详细信息

### ISSUE THREAD

**Issue by Espoir-L** [mipengine/mip-extensions#1224]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
开发者开发定制化模板时，由于cli里的debug信息不完善，导致开发者在开发模板的时候，追查问题比较难，得到的相关信息比较少，影响开发体验；

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
建议首先细化开发中遇到的问题，细化信息，并且在mip2的cli中完善这块功能；

**Comment by VenyXiong** [comment]
在mip2-cli中一并解决
