### ISSUE TITLE
mip-sidebar 在快速点击触发 open 事件两次会导致 mask 消失

### ISSUE THREAD

**Issue by clark-t** [mipengine/mip-extensions#1225]
**BUG 描述**
官网的组件 mip-sidebar 使用预览就能复现，快速点击 “Open mip-sidebar” 两次，会看到 mask 消失，同时侧边栏的滑出动画并未中断直至侧边栏完全展开，这时就没法通过点击 mask 收回 sidebar 了。

这个 bug 的触发场景是，页面未做点击防抖的情况下，非常容易就导致 sidebar 展开后无法收回，因此建议修复。

**复现步骤**
1. 打开 [mipengine.org 的 mip-sidebar ](https://www.mipengine.org/examples/mip-extensions/mip-sidebar.html) 点击预览
2. 双击 “Open mip-sidebar”，失败了不要紧，加油多试几次就复现了

**期望结果**
双击 “Open mip-sidebar” sidebar 正常展开且 mask 不消失

**截图**

![截图](http://boscdn.bpc.baidu.com/assets/bug/sidebar-b50dfdfc.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by caoru828** [comment]
2.0解决了这个问题
