### ISSUE TITLE
希望提供Google Analytics统计组件

### ISSUE THREAD

**Issue by halfer53** [mipengine/mip-extensions#1255]
**要解决什么问题**
提供Google Analytics 统计组件

**描述一下你理想中的解决方案**
支持Google Analytics 统计, 包括page和event

**描述你的备选方案**
根据 AMP Analytics 自己再为MIP写一个, 
AMP-Analytics: https://github.com/ampproject/amphtml/tree/master/extensions/amp-analytics/0.1

**补充信息**
补充其他信息，如截图等

**Comment by jenkey2011** [comment]
有的 [mip-stats-google 谷歌分析](https://github.com/mipengine/mip-extensions-platform/tree/master/mip-stats-google)
