### ISSUE TITLE
mip-infinitescroll

### ISSUE THREAD

**Issue by allen886** [mipengine/mip-extensions#1282]
**BUG 描述**
清晰和准确的描述 Bug 是什么
反复试了多次 还是无法解决这个问题，返回的数据如图 ，没什么错吧？怎么模板就是不渲染

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图
![image](https://user-images.githubusercontent.com/23253054/48324023-12bb8080-e66a-11e8-9aa3-447094629098.png)

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by VenyXiong** [comment]
可以给出更详细的使用示例页面么？
