### ISSUE TITLE
mip-showmore 组件和<mip-img>组件中属性popup 不兼容 的bug

### ISSUE THREAD

**Issue by gom3250** [mipengine/mip-extensions#1283]
**BUG 描述**
mip-showmore和<mip-img>的兼容问题

**复现步骤**
当mip-showmore 组件收起内容，刚好盖到图片的时候，并且图片组件有popup属性，点击mip-showmore 组件的展开，会同时点击图片。

**期望结果**
点击展开的时候不要同时放大图片

**截图**
测试地址：https://m.cr173.com/mipx/13568.html
![asd](https://user-images.githubusercontent.com/23326408/48400914-a2445a80-e762-11e8-9b85-664bd7f15c6f.jpg)

**机型**
安卓，苹果

**Comment by tfciw** [comment]
![image](https://user-images.githubusercontent.com/18052602/48693467-820a1500-ec14-11e8-8ef2-d16b18001194.png)
建议用click触发，不会引发点透问题
