### ISSUE TITLE
mip-list组件bug，如果页面调用多个组件的时候改变的永远只是第一个div里面的内容

### ISSUE THREAD

**Issue by caoru828** [mipengine/mip-extensions#1284]
**BUG 描述**
清晰和准确的描述 Bug 是什么

由于组件内写死了class，组件逻辑用document.querySelector('.mip-list-more')获取button，导致如果页面调用多个组件的时候改变的永远只是第一个div里面的内容
![image](https://user-images.githubusercontent.com/27049480/48407769-8f398680-e772-11e8-8cfa-433d56e779e1.png)

**复现步骤**
重新复现 Bug 的步骤

**期望结果**
清晰和准确的描述你期望的结果

**截图**
如果合适，添加问题相关的截图

**环境及版本信息:**
 - 浏览器 Version [e.g. 64]
 - mip-cli 版本

**其他信息**
其他补充信息

**Comment by zqcxxx** [comment]
已修复
