### ISSUE TITLE
mip-fixed  无法关闭

### ISSUE THREAD

**Issue by ChenAt** [mipengine/mip-extensions#1315]
![image](https://user-images.githubusercontent.com/13502799/50536067-81598c80-0b8b-11e9-8a22-88d54d91ab82.png)

官方的预览页面似乎也关不了？是我使用有问题吗。
https://www.mipengine.org/examples/mip-extensions/mip-fixed.html

**Comment by huanghuiquan** [comment]
这确实是bug，升级mip2后会出现这个bug，目前已在修复中~
