### ISSUE TITLE
mip  限制了a标签target="_blank" 属性建议

### ISSUE THREAD

**Issue by Chenhongxus** [mipengine/mip-extensions#156]
mip 的a标签加target="_blank"，该属性时 在打开 链接都生成 一个 新的窗口, 如果在同一个站访问多个页面时没有注意适当关掉一些窗口，会出现一大堆。手机配置比较低的会很卡。

**Comment by momofan** [comment]
我们已经有计划将这个限制下掉，详细请关注官网，多谢反馈

**Comment by pearlwang1106** [comment]
已上线

**Comment by Fidelw** [comment]
那应该在文档中删除掉这个限制
