### ISSUE TITLE
mip-carousel 建议添加样式

### ISSUE THREAD

**Issue by NowhereToRun** [mipengine/mip-extensions#252]
1.支持当前显示的图片和总图片的数量，例如右下角显示1/20（在轮播图很多的情况下有这种需求）。

2.支持滑动时的效果。 目前的是在滑动后显示下一张图片，没有拖动效果（参考swiper）。

**Comment by pearlwang1106** [comment]
@fengchuantao 跟进一下

**Comment by fengchuantao** [comment]
完成更新

**Comment by fengchuantao** [comment]
升级完成

**Comment by pearlwang1106** [comment]
@NowhereToRun 已经完成上线，可以查看线上效果，有问题可以及时反馈，如果没有问题可以close这个issue谢谢

**Comment by NowhereToRun** [comment]
你好，还有两个问题
1. 轮播图不支持图片懒加载
2. 默认图功能（这个是不是属于mip-img了）

**Comment by fengchuantao** [comment]
默认图是mip-img.懒加载后续升级 @NowhereToRun
