### ISSUE TITLE
mip-accordion 功能升级

### ISSUE THREAD

**Issue by pearlwang1106** [mipengine/mip-extensions#275]
- 升级组件，希望支持高度控制（可以设置高度阈值，超过高度才会显示『展开』『收起』按钮）

**Comment by pearlwang1106** [comment]
@fengchuantao 根据自己的工作给一下排期

**Comment by pearlwang1106** [comment]
加一个需求升级：展开收起的位置不做显示，让用户可以灵活控制

**Comment by pearlwang1106** [comment]
- 升级功能，希望字符数控制，另外考虑一下，现在展开收起的折叠需求比较多，可以看一下继续升级组件更合适，还是那这些功能单独拿出来封装一个mip-readmore组件更合适，如果单独封装，原组件需要做好兼容 @fengchuantao

**Comment by fengchuantao** [comment]
阀值与动画将列为一个新的组件，showmore.showmore为mip-accordion的高级版本 #356
