### ISSUE TITLE
mip-accordion 增加‘不记录用户展开历史’选项，增加展开动画

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#285]

**Comment by pearlwang1106** [comment]
@fengchuantao 开发 #275 的时候一起完善

**Comment by fengchuantao** [comment]
关于是否采用历史记录，请查看 [mip组件文档]( https://www.mipengine.org/doc/3-widget/3-customize-widget/accordion-widget.html), 阀值与动画将列为一个新的组件，showmore.showmore为mip-accordion的高级版本 #356
