### ISSUE TITLE
mip-storage支持存储

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip-extensions#298]
现在的mip页面都是在cdn下面，站长设置存储（如cookie）是不被建议的，因为会造成存储乱用，臃肿，安全性等问题，为此需要开发一套存储系统来统一管理。

**Comment by theSouthSea** [comment]
能不能再加一个过期时间的设置功能（localStorage）？比如一天，一周，一个月，一年等？

**Comment by wupengFEX** [comment]
@theSouthSea 目前的存储方案有两种：

1. 基于local storage的方式（直接调用我们提供的api就可以，目的是方便开发者，可以存储不敏感信息，隐私数据建议采用第二套方案），它可以设置对整个站点存储的过期时间（也可以不设置），但不针对某一个具体的字段；

2. 第二种方案是通过请求将数据发送给开发者（更加安全），让其自行进行管理，不管是设置cookie还是存储数据库均可，其过期时间由站长管理；

**Comment by wupengFEX** [comment]
### 存储方案

#### 一、前言
 为提供站点数据存储的功能，并且保证安全性和完整方案，开发一套存储方案来进行统一管理，包括站长管理存储，local storage方式。

#### 二、方案解读
通过初始化决定采用哪种方式，如new Storage(0)，0为local storage，1为站长管理存储；
- Local Storage存储方案
  - 对于不敏感信息，通过local storage的方式存储在当前域名下，由站长选择；
  - 如果是cache域名，通过mip策略进行管理，如果是站长自己的域名下，通过local storage原始方法进行存储管理，mip都已自行进行区分，只需调用mip提供的api就可以；
  - 该方案不保证信息的安全性，所以应该适当选取；
  - 每个站点对应local storage里面的一个key，如果在cache域名下，key为站长站点域名；
  - cache域名下，每个站点信息以json方式存储；
  - cache域名下，每个站点存储信息大小不超过4k；
  - cache域名下，cache域名下总存储空间为5M，根据浏览器不同而不同；

- 服务端存储方案
  - 保证安全性，但是会有延迟；
  - 存储完成后通过callback进行回调；
  - 每个该方式的callback都会维护一个回调队列，并以生成的id为key，发送请求成功后后端返回该id执行回调；
  - MIP只负责发起请求并将数据传给站长，需要站长自己维护存储操作功能（如种cookie或者存储数据库）；
  - id由我们由storage自动生成；

#### 三、模块划分
整个存储功能分为三块，整体调度模块（Storage），local storage实现模块，站长数据存储实现模块；

| 子模块名词   |      功能描述 |
|----------|------|
| 整体调度模块 | 通过构建参数判断使用哪种存储方式，并准确调度 |
| local storage实现模块 | 通过local storage方式进行set/get/rm/rmExpires/clear操作  |
| 站长数据存储实现模块 | 通过服务端管理数据并callback回开发者来控制存储过程 |

#### 四、详细设计
- 类描述

| Class Name   |  Class Description |
|----------|------|
| Storage | 收敛调度，形成唯一入口  |
| LocalStorage | 继承 Storage 类并实现其方法  |
| AsyncStorage | 继承 Storage类并实现其方法，指站长管理存储 |

- 关键类设计
  - LocalStorage，负责storage操作

    | 名称  | 描述 |
    |----------|------|
    | set | 设置存储数据，其中参数包括name,value,expire |
    | get | 获取存储数据，参数为name |
    | rm | 通过name删除数据存储 |
    | rmExpires | 删除所有过期数据，定位于全部local storage |
    | clear | 清除所有存储数据，只限于当前域名下的 |
  - 站长管理，负责数据管理操作

    | 名称  | 描述 |
    |----------|------|
    | request | 通过cors发起请求到后端，我们将数据传递给站长提供的后端（通过script中配置url），具体操作由后端具体执行 |


#### 五、总体流程
![总体流程](http://upload-images.jianshu.io/upload_images/2483150-369f711dee90e8a3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**六、存储方式**
- localStorage
  - key为domain
  - u为每次更新时间，每次对该站存储进行了操作都会更新该时间，为的是如果存储超限，根据u删除最长时间没进行操作的存储；
  - e为过期时间，他是整个站点的过期时间，站长可以设置，如果不设置则一直存在，直到用户删除ls。注：这里面没有对单个站点的单个存储设置过期时间，只对整站设置了，为的是减少json带来的冗余（占用空间比较大，从而移除其时间戳）
  - 数据形式
```
{
 “cookieName1”:  “my value1”
 “cookieName2”:  “my value2”
 “u”: “123123123123”,
 “e”: “123123123”
}
```
#### 八、注意点
- 单个站点如果4k的存储设置满了，那么会和ls和cookie一样不能在进行设置，抛出异常并回调给站长。
- 整个站点存储超限（5m，不同浏览器不同）会覆盖了最久没有操作的存储；

**Comment by wupengFEX** [comment]
### customStorage
customStorage是一套存储的使用方案，其中包括local storage使用方案和站长管理存储方案两种。

### 使用方式
```
var util = require('util');
var customStorage = new util.customStorage([param]);
```

#### API

- local storage方式API

    #### new util.customStorage(type)
    - customStorage类，用于初始化存储对象

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | type | number | type为存储类型，0表示local storage存储，1表示站长管理存储 |

    #### customStorage.set(name, value, [expire], [callback])
    - 设置当前站点下的存储；

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | name | string | 存储名称 |
    | value | string | 存储值 |
    | expire | number | 存储的过期时间，指的是整个站点local storage的过期时间，单位为s |
    | callback | Function | 存储出现问题时的回调，分为两种情况，一种是当前站点存储超限（4k），一种是超过local storage最大存储值（一般浏览器为5M），这个错误是针对所有站点的存储空间的 |

    下面是callback返回的error对象的结构

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | errCode | string | 错误号，21为当前站点超限，22位整个local storage存储空间不足 |
    | errMess | string | 错误信息 |

    #### customStorage.get(name)
    - 获取当前站点下的存储；

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | name | string | 存储名称 |

    #### customStorage.rm(name)
    - 删除当前站点下的存储；

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | name | string | 存储名称 |

    #### customStorage.rmExpires()
    - 删除整个local storage存储中过期的站点存储数据；

    #### customStorage.clear()
    - 清空当前站点下数据存储；

- 站长管理存储
    #### customStorage.request(opt)
    - 发起站长请求的函数，将数据通过请求传给站长，由其对数据进行设置或获取；

    | 参数名 | 参数类型 | 描述|
    |------|-------|-------|
    | type | string | (默认： “GET”)：请求方法 (“GET”, “POST”, or other) |
    | url | string | (默认： 当前地址)：发送请求的地址 |
    | data | Object |  (默认：none)：发送到服务器的数据；如果是GET请求，它会自动被作为参数拼接到url上。非String对象将通过 $.param 得到序列化字符串 |
    | beforeSend(xhr, settings) | Function | 请求发出前调用，它接收xhr对象和settings作为参数对象。如果它返回 false ，请求将被取消 |
    | success(data, status, xhr) | Function |  请求成功之后调用。传入返回后的数据，以及包含成功代码的字符串 |
    | error(xhr, errorType, error) | Function |  请求出错时调用。 (超时，解析错误，或者状态码不在HTTP 2xx) |
    | complete(xhr, status) | Function |  请求完成时调用，无论请求失败或成功 |

**Comment by xuexb** [comment]
`api#rmExpires`这个使用场景是啥呢? 是指在初始化页面时就执行下把过期的都清空?

本身`ls`不带时间管理, 我的实现是:

```js
// 存储: prefix_key = {key, value, now, expire}
ls.set(key, value, expire)

// 获取key
//     如果为空->null
//     如果过期->remove(key)->null
ls.get(key);

// 不管是否存在, 执行不报错, 返回值boolean表示是否成功删除
ls.remove(key);
```

使用方无需考虑时间管理, 当然这样就会导致没有使用`get`时缓存无法清空, 可以在页面首次`get`时做整个`ls`的脏检查.

---

只是个人看法. @wupengFEX

**Comment by wupengFEX** [comment]
@xuexb rmExpires是清除过期站点存储的API，调用时机为ls存储超限时，站长也可以手动调用，如果每次get都去清理会有时间成本的消耗，而且并不是一个刚需操作，因为最多占用空间仅为5M。

local storage有存储大小的限制，一般为5M，不同浏览器不同。如果ls存储超限，那么数据不会存储成功并且没有任何回调提示，导致结果是页面可能一些功能异常。MIP所做的存储策略是，如果ls超限，首先清除所有过期站点数据，如果都清除完发现存储还是不够，那么会清除到目前为止最久没有进行过操作的站点数据，旨在保证功能健全完整！

对于给每个站点加时间戳（对应rmExpires删除的api），是可选项，只给当前站点加时间戳的原因是减少json数据的冗余，ps：每个站点在cache域名下的数据是通过json存储。
