### ISSUE TITLE
mip-vd-tabs 升级支持异步请求数据

### ISSUE THREAD

**Issue by pearlwang1106** [mipengine/mip-extensions#319]

**Comment by momofan** [comment]
给一个解决方案

**Comment by zhao-ping** [comment]
mip-vd-tabs组件没有记录当前选项的功能，比如默认是选中第一个选项，然后用户点击了第二个选项，这时候刷新页面，页面上显示的选中项目仍然是第一个项目，本应该显示选中第二项。
建议：设置一个参数判断是否需要记录当先tabs的状态，如果需要就用localstorage记录状态，设置页面刷新时显示tabs之前记录到的状态
