### ISSUE TITLE
mip-lightbox 弹层建议 页面初始化时弹出层是否显示

### ISSUE THREAD

**Issue by jiangxuzh** [mipengine/mip-extensions#333]
1. 页面初始化后可能会需要直接弹出活动消息状态等，弹出层内有按钮可关闭弹出层，运营活动中可能常会有相关需求。建议组件添加可选字段，选择后页面初始化时显示弹出层。
2. 相应的是否可以添加cookie，适用于设备第一次进入时加载相应的组件，之后进入不加载。

**Comment by pearlwang1106** [comment]
- 收到建议，会从通用性的角度整体考虑一下
- 如果做的话这个用localSotrage就可以解决了，不用cookie

**Comment by momofan** [comment]
需要给出提示用户多少时间后消失

**Comment by wupengFEX** [comment]
自动弹层有损用户体验，官方暂不考虑支持 @jiangxuzh
