### ISSUE TITLE
mip-carousel 建议

### ISSUE THREAD

**Issue by jiangxuzh** [mipengine/mip-extensions#334]
轮播图的indicator半透明的背景是通过js添加的内联样式，无法用css更改。
![79ae37e3-0c5c-4faf-b94c-ecd2bdf65164](https://cloud.githubusercontent.com/assets/22673000/21682807/7399bfcc-d391-11e6-8e1d-8c445bdaabff.JPG)

**Comment by pearlwang1106** [comment]
@fengchuantao 看一下这里

**Comment by pearlwang1106** [comment]
这个功能我们已经升级组件并上线， @jiangxuzh 辛苦确认一下，如果没问题可以close这个issue :)

**Comment by jiangxuzh** [comment]
辛苦了
