### ISSUE TITLE
增加是否是微信内置浏览器和是否是ipad的判断

### ISSUE THREAD

**Issue by cutemantou** [mipengine/mip-extensions#339]
在mip内置模块中增加是否是微信内置浏览器和是否是ipad的判断 @wupengFEX

**Comment by pearlwang1106** [comment]
@wupengFEX 看一下

**Comment by cutemantou** [comment]
@wupengFEX

**Comment by wupengFEX** [comment]
@cutemantou 目前主要支持的是浏览器入口，对于web view我们会综合考虑一下看是否有必要加入platform中，有结论会及时通知！

**Comment by cutemantou** [comment]
是还没有上线吗，我看到mip文档中并没有添加上去

**Comment by wupengFEX** [comment]
@cutemantou 已上线，文档会尽快在官网更新，请关注！
