### ISSUE TITLE
mip-360doc-script组件地址无法使用

### ISSUE THREAD

**Issue by 360doc** [mipengine/mip-extensions#35]
组件于2016年11月10日  commit 并被 merge 到master 分支中。 根据docs 中MIP 扩展组件规范  的上线地址格式   https://mipcache.bdstatic.com/static/mip-360doc-script/latest/mip-360doc-script.js  无法访问。

**Comment by dannyliou** [comment]
一样的问题，文档里说是今天三点上线，可是现在还是404诺，难道还没上线？

**Comment by pearlwang1106** [comment]
文档有误，稍后修改文档，这是线上地址： https://mipcache.bdstatic.com/static/v1.2/mip-360doc-script.js
