### ISSUE TITLE
mip-stats-baidu  统计组件问题

### ISSUE THREAD

**Issue by hejieye** [mipengine/mip-extensions#350]
统计事件同时使用 click 和 load 的时候 去触发click的时候并没有生效 并且触发到了load。
现在我们遇到这个问题希望能够快点解决。http://m.iask.sina.com.cn/mib/tqmMWGJOfF.html

**Comment by pearlwang1106** [comment]
@fengchuantao 辛苦跟进一下

**Comment by fengchuantao** [comment]
@hejieye 线上已经修复。请确认一下效果。
