### ISSUE TITLE
mip-mustache 建议添加使用文档

### ISSUE THREAD

**Issue by NowhereToRun** [mipengine/mip-extensions#353]
这个是模板组件吧？

**Comment by pearlwang1106** [comment]
是的，这个上线后我们会添加使用文档到官网，预计下周上线

**Comment by pearlwang1106** [comment]
组件已经上线，参考使用文档 [mip-mustache 模板组件](https://www.mipengine.org/doc/3-widget/3-customize-widget/mustache-widget.html) 使用，如有问题，可以反馈

**Comment by xuexb** [comment]
@pearlwang1106 `mip-mustache 模板组件`链接404了 🐠

**Comment by pearlwang1106** [comment]
@xuexb 已更新
