### ISSUE TITLE
增加一个点击展开更多的组件

### ISSUE THREAD

**Issue by iVatin** [mipengine/mip-extensions#356]
增加一个点击展开更多的组件

**Comment by fengchuantao** [comment]
# showmore开发方案

#### 背景

由于现在站点对显示更多需求日益增强,对显示方案多元化需求增强。结合现有站点自我开发的组件进行融合处理。希望在mip中只有一个showmore组件。完成全mip通用的目标


## 现有组件分析


#### mip-down-hideshow 

[西西软件园](http://m.cr173.com/mipx/179440.html)


#### mip-hk-showarticle

百度好看 应该是混合式app页面


####   mip-content-readmore
[应届毕业生](http://mip.yjbys.com/company/4976.html)


## 组件功能实现


1. 实现任意组件对内容的打开关闭

2. 实现组件的内容的长短字数处理

3.  阀值控制(高度控制)

### 技术细节

#### 实现任意组件对内容的打开关闭

通过tag实现对需要关闭的内容进行选定。

#### 实现组件的内容的长短字数处理

通过获取dom节点text节点。匹配长度实现长短字数控制。

####  阈值控制

通过overflow: hidden样式控制阀值高度的处理。

**Comment by fengchuantao** [comment]
现行方案是这样，如果还有需求请在添加新功能

**Comment by fengchuantao** [comment]
已上线
