### ISSUE TITLE
不是说三点上线的么？

### ISSUE THREAD

**Issue by dannyliou** [mipengine/mip-extensions#36]
请问一下，不是说三点上线的么？为啥这个 https://mipcache.bdstatic.com/static/v1.1/mip-stats-ajk.js
返回还是404诺？

**Comment by pearlwang1106** [comment]
https://mipcache.bdstatic.com/static/v1.2/mip-stats-ajk.js  是这个地址，已经更新都 mip-stats-ajk 的readme了
