### ISSUE TITLE
mip-video poster上方显示播放按键，隐藏控制条

### ISSUE THREAD

**Issue by NowhereToRun** [mipengine/mip-extensions#387]
在播放视频前，显示poster时，不显示默认的控制条，在poster上方显示一个大的播放按键（样式可自定义）
这个可根据参数选择只是首次显示或者每次暂停都显示
参见新浪新闻，搜狐新闻
请问这个是你们可以给组件升级呢 还是我们自己封装

**Comment by pearlwang1106** [comment]
- 首先请问一下你这个需求是否急需
- 另外，这次先我们这边做吧，不过现在春节休假了，要年后才能排期

**Comment by pearlwang1106** [comment]
@fengchuantao

**Comment by momofan** [comment]
已上线解决，采用主流视频网站的交互方式
