### ISSUE TITLE
mip-lightbox失效问题

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#399]
mip-form和mip-lightbox组件有个bug
你们可以尝试同一个页面引入这两个组件，当使用form表单提交后，然后把页面刷新，这时候lightbox弹层就会失效，不知道什么原因
我测试的浏览器是360手机模式，谷歌移动端模式。两个浏览器都是这样的问题。
但是我用iPhone7的自带浏览器safari没发现问题。求官方解决
---- tvmkl@qq.com

**Comment by pearlwang1106** [comment]
我来跟进一下

**Comment by pearlwang1106** [comment]
暂时定位问题是：360浏览器在模拟移动端的时候，不支持touch点击事件，这应该是360浏览器的兼容性问题。暂时没有收到大家关于手机上的此类问题的反馈，所以先不做处理，如果大家在测试过程中遇到真机环境的问题，可随时反馈过来，我们会及时解决
