### ISSUE TITLE
mip-nav-slidedown 的 showbrand 不起作用

### ISSUE THREAD

**Issue by fshare** [mipengine/mip-extensions#401]
showbrand为0或1是<a href=“” class="navbar-brand"></a>都显示，同时能不能增加参数，可以控制.navbar-brand 的链接内容，如：<a href=“” class="navbar-brand">' + brandtext + '</a>

**Comment by fshare** [comment]
showbrand为0或1是<a href=“” class="navbar-brand"></a>都显示，同时能不能增加参数，可以控制.navbar-brand 的链接内容，如：<a href=“” class="navbar-brand">' + brandtext + '</a>

**Comment by fshare** [comment]
或者 .navbar-header内容可以自定义，页面如果存在，则不appendTo新的

**Comment by jennyliang220** [comment]
需求已经收到。新版组件会做以下改动：
1. 修复showbrand问题。
2. 增加data-brandname 参数，用户填写字符串，会展示在.navbar-brand中。可以通过为class添加类来定义样式。data-brandname 参数仅在showbrand=1（显示左上角链接）时生效
