### ISSUE TITLE
多图自动轮播，图片不显示

### ISSUE THREAD

**Issue by mabaoliang216** [mipengine/mip-extensions#429]
添加多图自动轮播，加载图片大于三张时，轮播过程中第三张不显示。鼠标或者手滑参与翻页轮播正常。请尽快修复自动轮播时出现的问题。

**Comment by fengchuantao** [comment]
以更新上线

**Comment by Fidelw** [comment]
.mip-layout-size-defined {
    overflow: hidden !important;
}

**Comment by Fidelw** [comment]
图片显示不全啊

**Comment by Fidelw** [comment]
我用了菜单组件，然后再用这个轮播组件，轮播组件会有一部分无法显示

**Comment by pearlwang1106** [comment]
@Fidelw 能给一个
