### ISSUE TITLE
mip-semi-fixed 半固定组件

### ISSUE THREAD

**Issue by hfhd** [mipengine/mip-extensions#438]
### 目录

- 需求简介
- 业界背景
- 补充需求
- 实现思路

### 需求简介

mip-semi-fixed 是一个基于mip-fixed组件的基础上，添加页面滚动效果后再实现的悬浮的组件。
组件需求是：组件最初可处于页面的任意位置，当页面向上滚动到一定位置时，组件再悬浮固定定位（悬浮的位置可定制距离顶部或者是底部的距离，同时组件内元素的样式可以修改），当页面回滚到原位置时目标元素则回到原始状态（包括最初的位置和样式）。

- 需求组件：#337 
- 需求组件：#409 
- 业界需求：[pc6 下载页面](http://m.pc6.com/s/109066)
- 业界需求：[cr173 页面](http://m.cr173.com/x/266748)
- 业界需求：[火凤游戏网](http://m.xiazai188.com/z/7378.html)

### 业界背景

目前业内针对这种滚动页面定位的情况一般使用两种逻辑来写
（1）将页面滚动前和滚动后的两个状态分成两个模块在html中写出，只是其中滚动前的模块显示，滚动后的模块隐藏，当页面向上滚动时两种状态切换，滚动前的模块隐藏，滚动后的模块显示；当回滚页面时又再进行切换，回到初始状态；

（2）页面滚动前和滚动后的两种状态都直接写在js中，针对这个部分整个html中都只有一个模块，当页面向上滚动时，调用js替换页面滚动前的position为fixed，同时替换css样式；当页面回滚时，再次通过js替换成为最初状态。

目前业内使用最多的是第二种方法，两种方法有如下优缺点：
（1）第一种：
	
- 优点： 1.  js仅需根据需求写两个模块显示隐藏切换即可；	     
              2.用户使用比较灵活，滚动后的状态只需通过css就可以修改，不需要再通过调用js来修改；
- 缺点：html中需要写两个模块，比较累赘；

（2）第二种：

- 优点：html中只需一个模块，html会比较简单；

- 缺点：js内容会比较多，需要直接替换原来的状态，包括position位置或者是css样式等，而且每个用

     户对样式的需求不同，position定位也不同，所以js的要求会比较多，而且对于用户来说也不是很灵活；

选择开发方法：

考虑到满足用户的各种需求，如需要在滚动后的模块里面添加一些与原显示状态下的模块中没有的内容，或者是更方便的更改滚动后的模块中的样式，以及组件的悬浮定位位置需求等等！所以在制定mip-semi-fixed组件开发的方案中，选择第一种方法来进行开发。

### 补充需求
	
滚动前显示模块标签和组件内部标签不可定的过死，仍然可以在内部嵌套其他的任何的标签或者是组件。

### 实现思路
（1）页面中存在两个模块（类似mip-lightbox组件，分为button和mip-lightbox两个模块），一个模块显示（div标签），另一个模块隐藏（mip-semi-fixed组件），其中显示模块是页面滚动之前的初始状态，隐藏模块为组件添加部分，是页面滚动之后的状态（用户可以灵活的在css中修改自己所需要的样式）；

（2）显示模块（div标签）可在页面内部任意位置使用，隐藏组件display:none隐藏；
	
（3）mip-semi-fixed内部所需属性参数（由官方提供fixed接口）：threshold；

	   - threshold：页面滚动到的指定位置的临界值，初始参数为150px；

（4）当页面向上滚动到threshold位置时，即（页面的scrollTop >= threshold）,原显示的div标签隐藏，原隐藏的mip-semi-fixed组件显示； 
	
（5）当页面回滚到threshold位置时，mip-semi-fixed组件隐藏，div标签显示，回到初始状态。

**Comment by pearlwang1106** [comment]
@hfhd 看一下这个页面（http://m.qbaobei.com/d/32214.html ）的滑动定位需求，看我们能不能兼容

**Comment by cutemantou** [comment]
这个组件外看是否能嵌套一个mip-vd-tabs,该悬浮的模块是一个tab选项卡，实现相应内容的切换，点击tab中相应的选项，定位到相应内容的顶部

**Comment by pearlwang1106** [comment]
@cutemantou 从理论上来讲 tab 和滑动固定是不冲突的，可以在组件内嵌套tab组件，但是之前看过你的需求页面，点击tab的时候，tab中的内容要回滚到tab下面来，这个交互应该是 tab 组件来完成的。

同时，考虑到 mip-semi-fixed 组件在固定态是会固定住其内部所有内容，而 tab 组件的tab和content都是在组件中的，如果两个组件同时使用的话，会有问题

所以，还是希望分开考虑

**Comment by cutemantou** [comment]
那带有回滚的tab切换这个操作我自己实现，fixed组件用你们的

**Comment by pearlwang1106** [comment]
理论上是可以的，等我们上线，你测试一下

**Comment by hfhd** [comment]
组件已经提交了

**Comment by pearlwang1106** [comment]
@hfhd 请问提交到哪里了，pr地址发一下

**Comment by hfhd** [comment]
https://github.com/hfhd/mip-extensions-1/tree/master/mip-semi-fixed

**Comment by 785423753** [comment]
请问这个组件上线了吗

**Comment by hfhd** [comment]
已经上线了





在 2017-02-28 11:28:22，"tanyanfei" <notifications@github.com> 写道：


请问这个组件上线了吗
