### ISSUE TITLE
mip-360doc-script 组件代码更新问题

### ISSUE THREAD

**Issue by 360doc** [mipengine/mip-extensions#46]
2016年11月11日 上午提交的版本，已经 commit 并且 merge ，但是线上文件https://mipcache.bdstatic.com/static/v1.2/mip-360doc-script.js  还是旧版本

**Comment by pearlwang1106** [comment]
看一下https://mipcache.bdstatic.com/static/v1/mip-360doc-script/mip-360doc-script.js 是不是最新的，你们组件的readme 里对应的路径我们也改了
