### ISSUE TITLE
mip-analytics：可配置 queryString 以便收集更多信息 

### ISSUE THREAD

**Issue by asuka999** [mipengine/mip-extensions#463]
queryString 可以配置为 function。
或者增加变量的域（推荐，易实现，要考虑问题较少。
如：
```
"queryString": {
    "id": "${id}",
}
```
id 是可以从当前 dom 的 data-id 获取的 。

**Comment by pearlwang1106** [comment]
@asuka999 理解你的意思，我们这边的方案是，除了公用参数写在<script type="application/json"></script> 的配置中，特殊参数可以写在节点中 比如 <div ...  data-clic="{a:1,b:2}"></div> 这种形式

这是目前我们打算升级的方案，你这边看这样有什么问题吗，对于你们的使用还有什么需求需要满足吗
