### ISSUE TITLE
mip-list: 异步加载支持自定义查询参数

### ISSUE THREAD

**Issue by pangz1** [mipengine/mip-extensions#467]
支持src属性带queryString，或者添加一个属性可以配置查询参数

**Comment by pearlwang1106** [comment]
@pangz1 你好，想了解一下，你这个查询参数每次都是固定的，还是在翻页查看更多的情况下会发生变化呢？

**Comment by pangz1** [comment]
@pearlwang1106 翻页查看更多只会改变pageNum 这个参数，但是因为多个页面用同一套模板，在不同的页面我请求的后端接口可能会带其他参数，比如分类

**Comment by pearlwang1106** [comment]
所以参数最好是你们可配，而不是写死？

**Comment by pearlwang1106** [comment]
你们多个页面使用同一个模板的时候，不同参数是如何设置的
