### ISSUE TITLE
mip-lightbox 能否升级或增加一个支持内部滚动的弹层

### ISSUE THREAD

**Issue by qiqishunli** [mipengine/mip-extensions#470]
我们有一个评价组件需要使用弹层并且内部的内容需要滚动查看，非常着急，希望升级一下mip-lightbox当内容超过一屏时支持内部滚动，或者新增一个支持内部滚动的组件。

**Comment by pearlwang1106** [comment]
收到，我们会调研一下，然后给出反馈

**Comment by pearlwang1106** [comment]
是否有尝试过用css实现，组件里并没有阻止滚动事件
