### ISSUE TITLE
video组件问题

### ISSUE THREAD

**Issue by 360doc** [mipengine/mip-extensions#481]
mip-video组件无法播放。
例子1：http://www.360doc.cn/mip/test9.html ，使用mip-video组件，点击播放按钮后无反应。
例子2：http://www.360doc.cn/mip/test10.html ，没有使用mip-video组件，直接用video标签，可以播放。

**Comment by pearlwang1106** [comment]
@fengchuantao 辛苦跟进一下，找到具体原因

**Comment by fengchuantao** [comment]
高优跟进中

**Comment by wupengFEX** [comment]
@360doc [#113](https://github.com/mipengine/mip/pull/113/files#diff-aaa742b611a5a5da344ba0e463b02909)已上线！
