### ISSUE TITLE
MIP-share组件问题

### ISSUE THREAD

**Issue by GKrace** [mipengine/mip-extensions#483]
mip-share 分享 组件 在安卓微信中不起作用！苹果可以！手机浏览器中 有时显示QQ空间和新浪微博分享效果~多数情况是这个样子。

**Comment by pearlwang1106** [comment]
收到问题，等我们复现和定位一下给你回复

**Comment by pearlwang1106** [comment]
@GKrace 『手机浏览器中 有时显示QQ空间和新浪微博分享效果~多数情况是这个样子。』这个问题在ios 和andriod下都会复现吗，具体是什么浏览器？

**Comment by pearlwang1106** [comment]
#491 问题已定位：由于浏览器类型判断错误导致的，现已修复，会尽快上线

**Comment by xiaojinping** [comment]
1:PC端 mip的分享组件，只可以分享到QQ空间，新浪微博，我们公司的需求是需要分享到朋友圈去。
2:用微信打开，朋友圈和微信好友这两个根本点不开，无效的。同样的也只有qq空间和新浪微博
