### ISSUE TITLE
页面退回上一级问题

### ISSUE THREAD

**Issue by 785423753** [mipengine/mip-extensions#484]

**Comment by wupengFEX** [comment]
@785423753 问题具体场景，描述麻烦提供一下

**Comment by 785423753** [comment]
javascript:history.back(-1)

**Comment by wupengFEX** [comment]
@785423753 尝试在页面加入该方式，没有出现异常，请提供出现问题的页面，以及具体问题是什么

**Comment by 785423753** [comment]
<mip-link href="javascript:history.back(-1)">返回</mip-link>   可以这样用吗？退回上一页

**Comment by 785423753** [comment]
<a href="javascript:history.back(-1)">    就是这个功能，请问要怎么实现

**Comment by 785423753** [comment]
就是怎么返回上一页的问题，  javascript:history.back(-1)这个并不能加在mip-link组件上

**Comment by 785423753** [comment]
浏览器的后退功能

**Comment by 785423753** [comment]
https://m.huodongjia.com/event-11361688.html

**Comment by jennyliang220** [comment]
线下沟通结论：由官方支持，扩展mip-link组件。具体逻辑为：

- 在百度结果页异步打开时，为和头部后退按钮避免功能重复，不支持后退。
