### ISSUE TITLE
mip-appdl 功能优化

### ISSUE THREAD

**Issue by wycmip** [mipengine/mip-extensions#490]
mip-appdl 下载控件，现在除了安卓，IOS设备才能显示下载按钮，其他设备下，都不展示，变成空白。对于用户相当的不友好。一个建议，就增加一个属性，设备默认链接。如果其他设备下，就显示该链接按钮。从而增加友好性。

**Comment by pearlwang1106** [comment]
@fengchuantao 跟进一下看看

**Comment by momofan** [comment]
已上线解决  文档更新 @GKrace
