### ISSUE TITLE
有关网盟扩展广告的一个问题

### ISSUE THREAD

**Issue by zerosoul** [mipengine/mip-extensions#497]
嵌入式网盟扩展广告展示有问题。
以前把广告代码放到哪儿，该广告就会加载到哪儿，现在有时会出现在页面底部。
可能是广告的加载策略变了，因为看代码是广告直接append到body底部了。
![image](https://cloud.githubusercontent.com/assets/2985895/23983253/fd84533a-0a4d-11e7-95a1-d49453c05f73.png)

**问题不能稳定复现，需要多刷几次**...
这点表示略蛋疼o(╯□╰)o

示例页面URL：http://m.fh21.com.cn/iask/view/103464201.html?88888

问题截图：
![image](https://cloud.githubusercontent.com/assets/2985895/23983221/cf614d78-0a4d-11e7-9af4-066e026f11d9.png)

涉及的自定义组件：https://github.com/mipengine/mip-extensions/tree/master/mip-ck-browser

出问题的广告类型：https://www.mipengine.org/doc/3-widget/5-ad-widget/ad-baidu-wm-ext-widget.html

**Comment by pearlwang1106** [comment]
你好，我这边用手机看了一下，并没有复现你说的情况，我看你们的使用情况是在你们自己的组件中嵌入了广告，可以构造一个测试页面看看只有 mip-ad 没有 mip-ck-browser 的情况是否会复现这个问题

**Comment by zerosoul** [comment]
恩，是的，我们在mip-ck-browser组件里嵌入了这种网盟广告，理论基础就是网盟广告代码放哪儿，就会在哪儿加载，相当长的一段时间这种策略是没有问题的。现在网盟广告直接append到body底部了，这种加载扩展网盟策略的改变是临时的还是永久的？如果永久的，我们只好改组件的逻辑了。

**Comment by pearlwang1106** [comment]
如果你直接使用 `mip-ad` 组件，会有这个问题吗

**Comment by zerosoul** [comment]
没有，可以现在的需求就是使用mip-ck-browser组件加载mip-ad广告...

**Comment by pearlwang1106** [comment]
如果直接使用 `mip-ad` 标签是 OK 的，说明应该是 `mip-ck-browser` 组件影响了广告，可以看看在 `mip-ck-browser` 中追查一下原因
