### ISSUE TITLE
mip-form表单

### ISSUE THREAD

**Issue by 520huihuizhou** [mipengine/mip-extensions#516]
![default](https://cloud.githubusercontent.com/assets/24927625/24235688/6a57a5bc-0fd9-11e7-9dc2-1237d7b6af4d.png)这个写要用到的，怎么实现，有支持的组件吗

**Comment by pearlwang1106** [comment]
@jennyliang220 看下

**Comment by jennyliang220** [comment]
个性化的需求，可以自己封装组件。如果 @520huihuizhou 觉得通用性好，也可以提交到官方组件库
