### ISSUE TITLE
mip-accordion 折叠节点

### ISSUE THREAD

**Issue by 520huihuizhou** [mipengine/mip-extensions#517]
这是个什么情况，加了expanded 默认展开的 mip-accordion 子节点需要配置此属性，只有在 mip-accordion 的 type 属性值为 manual 时 才会生效，加了之后后边的不应该跟着变吗？开始是不行的，点击一次之后就正常了，求解释
![default](https://cloud.githubusercontent.com/assets/24927625/24278446/d26af7bc-107e-11e7-9e5d-bef98ecb9397.png)
![qq 20170324104129](https://cloud.githubusercontent.com/assets/24927625/24278448/d59268e4-107e-11e7-87a9-8d7ad939e531.png)

**Comment by pearlwang1106** [comment]
能提供一下代码片段和页面 url 吗

**Comment by wupengFEX** [comment]
@GKrace 了解一下情况并跟进

**Comment by GKrace** [comment]
1.如果您想问的是，为什么添加了 expanded 属性后 mip-accordion 组件不生效？ 那么，经我们测试，此属性是没问题的，请您自行检查网站中的代码是否存在其他问题。
2.如果您想问的是，如何用 mip-accordion 组件实现标题切换 + 默认节点展示功能，请参考 [mip-accordion](https://www.mipengine.org/doc/3-widget/3-customize-widget/accordion-widget.html) 组件文档 中的
“标题切换形式” 示例代码。
