### ISSUE TITLE
mip-infinitescroll 无限滚动组件报错

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#518]
mip.js:2 Uncaught (in promise) Error: JSONP request to http://192.168.2.46/info/news/getJSONNewsPager.shtml?sectionId=1210&sectionIdSecond=41&page=2& timed out
at mip.js:2  
报错图片见文章评论：http://www.cnblogs.com/mipengine/p/21_mip_infinitescroll.html

**Comment by 846560245** [comment]
请问这个问题解决了吗？

**Comment by 846560245** [comment]
@jennyliang220

**Comment by JamesSky** [comment]
我们开发也遇到了问题，正常jq的jsonp能接到数据，用无限滚动组件后报错callback为定义的错误～。心情甚是不好

**Comment by 846560245** [comment]
我的其实是List控件遇到的这种问题，接口接收传过来的callback，返回时把接收的加上就可以了

**Comment by JamesSky** [comment]
什么意思呢？现在返回数据是callback(...)，里面是mip要求的static和items格式，前端mip中怎么接呢

**Comment by 846560245** [comment]
Result = context.Request["callback"];
Result += "(" + JsonConvert.SerializeObject(new { status = 0, data = new { items = list, isEnd = isEnd } }) + ")";

**Comment by JamesSky** [comment]
心塞啊，2天了，没有一点头绪。你那里有上线的demo么，实在不行就直接显示几条数据吧。尴尬症犯了～

**Comment by JamesSky** [comment]
项目组给力，已解决

**Comment by lvdilenggui** [comment]
@JamesSky 怎么解决啊？

**Comment by JamesSky** [comment]
就严格按照官网的数据格式操作。前台直接写请求，后台先接收url中callback的值（假如是jsonp_11），然后拼接
jsonp_11({
    status: 0, 
    data: { 
        items: [your list]
    }
})
返回给前台，就可以了

**Comment by momofan** [comment]
已解决

**Comment by liucuicui1** [comment]
@JamesSky @momofan @jennyliang220 @lvdilenggui 求帮助，我遇到同样的问题，后台数据格式跟官网的一样，返回到前台后获取不到数据，也是跟官网的一样获取不到哦，在线等 ~ 急~
