### ISSUE TITLE
mip-fixed关闭漂浮时，可操作其他dom，需求

### ISSUE THREAD

**Issue by liuhen0806** [mipengine/mip-extensions#522]
mip-fixed,使用顶部漂浮时候，为了使页面中 内容不被漂浮遮挡，页面中加了一个空的占位dom，当点击漂浮关闭的时候，漂浮关闭了，但是占位dom依然存在，现在需要把占位dom也隐藏

![qq 20170328085803](https://cloud.githubusercontent.com/assets/23732056/24384262/20c6ada2-1395-11e7-952b-13fc9cf91d02.png)
![qq 20170328090102](https://cloud.githubusercontent.com/assets/23732056/24384266/2981da8e-1395-11e7-81bf-011cf6e2d631.png)

**Comment by momofan** [comment]
辛苦提供一下case 页面地址，我来跟进 fix

**Comment by pearlwang1106** [comment]
关注一下 #523
