### ISSUE TITLE
mip-semi-fixed 组件增加关闭按钮建议

### ISSUE THREAD

**Issue by qlh99** [mipengine/mip-extensions#523]
示例：http://ask.39.net/html5/mip/mip1.html  
mip-semi-fixed不脱离文档流没有关闭按钮。希望能增加关闭按钮。
mip-fixed 脱离文档流页面。

**Comment by pearlwang1106** [comment]
#525

**Comment by pearlwang1106** [comment]
已上线，参考文档：[mip-semi-fixed 滑动悬浮组件](https://www.mipengine.org/doc/3-widget/3-customize-widget/semi-fixed-widget.html)

**Comment by qlh99** [comment]
bug：点击关闭按钮会继承下面的a链接，
![image](https://cloud.githubusercontent.com/assets/14540761/24532437/16b94724-15f3-11e7-88dd-94e86defcb65.png)

http://ask.39.net/html5/mip/mip-ask1.5ycm.html

**Comment by pearlwang1106** [comment]
收到，今天会修复一版

**Comment by qlh99** [comment]
谢啦
