### ISSUE TITLE
mip-fixed去掉宽度10%的限制

### ISSUE THREAD

**Issue by qiqishunli** [mipengine/mip-extensions#526]
10%的限制对于我们的评价图标来说太小了，图标只能现在一半，希望能去掉这个限制
![image](https://cloud.githubusercontent.com/assets/10528613/24440915/8bb8fe7c-1489-11e7-874c-e71fce36dcf2.png)

**Comment by pearlwang1106** [comment]
提供一个可以访问的页面地址
