### ISSUE TITLE
mip-link 组件功能升级说明

### ISSUE THREAD

**Issue by pearlwang1106** [mipengine/mip-extensions#527]
## 背景描述

某个页面被多少页面引用（在其他页面上有指向这个页面的 `a` 标签），是搜索引擎判断这个页面价值的其中一个因子。这里的搜索引擎不只是指百度，还包括国内外其他的搜索引擎。

MIP 在最初设计 MIP url 跳转逻辑实现时，并未考虑到搜索引擎判断页面价值的这一个点，设计了 `mip-link` 组件代替了部分 `a` 标签功能，打断了搜索引擎通过 `a` 标签去判断页面的价值，导致使用了 `mip-link` 组件的 mip 页面的页面价值收到了影响，与此同时，也影响了搜索引擎的搜路和连接关系的判断。

基于上述背景，我们 MIP 项目组需要升级 `mip-link` 组件以解决上述问题。

## 实现方案

升级 `mip-link` 组件，其组件渲染后，`mip-link` 的内容会用生成的一个 `a` 标签包裹，此 `a` 标签放在 `mip-link` 的节点下，渲染后 `DOM` 结构如下：

```html
before:
<mip-link href="http://m.baidu.com">链接文字</mip-link>

after:
<mip-link><a href="http://m.baidu.com">链接文字</a></mip-link>
```

## 影响

对目前已经使用 `mip-link` 组件的页面造成的主要影响集中在页面样式上，目前我们会对 `padding`、`margin`、`display` 和 `color` 做兼容，经过反复测试，目前梳理出来如下定义的 css 可能存在样式问题： `nth`、 `.a > .b >  mip-link`，所以如果站长发现页面样式有问题，需要对已有样式进行相应调整。现在我们的组件正在测试中，具体上线请大家关注[官网动态](https://www.mipengine.org/timeline.html#all)和 本条 issue 的进展

**Comment by zhao-ping** [comment]
mip-link会自己把链接的字体单位改成px,我用的是rem单位，改成px后，手机屏幕横屏时，样式就不合适了，个人觉得这样的设计不合理，请更正，谢谢！
