### ISSUE TITLE
弹窗组件的问题

### ISSUE THREAD

**Issue by wuhanfeiyou** [mipengine/mip-extensions#539]
https://www.mipengine.org/doc/3-widget/3-customize-widget/lightbox-widget.html
目前的弹层组件，如果我加在a标签上。。那么他会阻止我a标签的href事件。。
看能不能加个参数。。来控制是否阻止当前标签的自身功能。？
或者我想给一个元素加除了弹层外的其他效果，该如何加呢？

**Comment by wupengFEX** [comment]
我理解你所说的问题是绑定 tap 事件之后阻止了 a 标签的默认行为，目前 MIP 这样来做是比较合理的，否则事件执行很大程度上会受到默认行为干扰。
你所说的这种特殊需求可以封装自己的组件来满足。
