### ISSUE TITLE
mip-list组件支持动态渲染链接

### ISSUE THREAD

**Issue by dengzehua** [mipengine/mip-extensions#562]
目前mip-list不支持动态渲染链接，给使用该组件带来很大局限性
```
<mip-list src="https://xxx/api" preLoad>
	<template type="mip-mustache">
		<div>
			<div class="li">
			<a href='{{{url}}}' target='_blank'>
				<div class='li'>
					<div class='t_tit'>{{{title}}}</div>
					<div class='t_cont'>{{{digest}}}</div>
					<div class='t_b'>
						<span class='relevant'></span>
						<span class='download_icon'></span>
						<span class='l_num' >{{max_post_id}}</span>
					</div>
				</div>
			</a>
			</div>
		</div>
	</template>
</mip-list>
```
使用以上代码渲染页面无法通过校验，提示：标签'a'中的属性'href'的属性值'{{{url}}}'无效，限制了同一个mip-list下只能渲染同一个站点下的内容。

将`<a href='{{{url}}}' target='_blank'>`改成`<a href='https://xxxx/{{{url}}}' target='_blank'>`后，在源mip页面可以正常渲染但在m.baidu下地址被替换成 `<a href='https://xxxx/%7B%7B%7Burl%7D%7D%7D' target='_blank'>`,彻底无法使用mip-list实现动态渲染链接功能。

**Comment by wupengFEX** [comment]
@dengzehua 这个是已知问题，目前已经在计划中，并会在近期升级上线，实时状态我们会同步在这里！

**Comment by JamesSky** [comment]
`ERROR → line 322,col 15: 标签'mip-link'中的属性'href'的属性值'{{newsUrl}}'无效`
我也遇到了这个问题，哈哈，什么时候能解决呢。。。

**Comment by JamesSky** [comment]
我现在需要换掉这个写法么

**Comment by pearlwang1106** [comment]
我们正在升级这块的校验

**Comment by wupengFEX** [comment]
#682

**Comment by dongshihao** [comment]
校验于`2017-08-01`上线升级完毕。
