### ISSUE TITLE
mip-sidebar 侧边栏组件，在android、pc浏览器下的兼容性问题

### ISSUE THREAD

**Issue by NamedDavidChan** [mipengine/mip-extensions#580]
问题描述：当使用android的浏览器和PC浏览器调试模式时候时，点开sidebar，通过点击mask阴影部分来关闭sidebar。如果阴影部分下面有链接，则点击该部分会跳转到链接。

PS：iOS的浏览器好像工作正常。

希望尽快修复！！

**Comment by momofan** [comment]
@pearlwang1106 尽快修复

**Comment by zhiruoyu88** [comment]
5s下，触发按钮在mask下边，点击触发按钮会触发mask里边的链接

**Comment by pearlwang1106** [comment]
正则修复这个问题，正在开发中

**Comment by jennyliang220** [comment]
已上线
