### ISSUE TITLE
mip-infinitescroll存在的问题

### ISSUE THREAD

**Issue by JamesSky** [mipengine/mip-extensions#591]
当我默认不写rn的时候默认数据显示条数为30条，但是如果数据不够30条时，会一直显示正在加载中。正常的显示应该是数据加载完毕。

**Comment by pearlwang1106** [comment]
能提供一下 页面url 吗

**Comment by JamesSky** [comment]
http://mobile.51uyi.com/video/article/48493-160.html

**Comment by pearlwang1106** [comment]
是这样的，rn 是控制请求结束的变量，我们默认值设置的是20，所以你们结果不大于20的时候是不会结束的，这个我们会修改一下组件的默认值，05月19日完成上线
