### ISSUE TITLE
mip-cache改写mustache模板内图片src问题

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#592]
mustache属于前端模板，<template>html源码中会出现 `<mip-img src="{{imgUrl}}">`字样，cache改写后会乱码。

需要解决：
1. cache不改写template内容
2. template渲染后，异步从cache获取图片src

页面url： 
- 原页面：https://mobile.51uyi.com/video/article/48493-160.html
- cache页面： https://mipcache.bdstatic.com/c/s/mobile.51uyi.com/video/article/48493-160.html

**Comment by momofan** [comment]
cache 需要更新改写的 lib，解决最终问题，目前在测试阶段
