### ISSUE TITLE
mip-video显示问题

### ISSUE THREAD

**Issue by JamesSky** [mipengine/mip-extensions#594]
## 问题描述
在页面中显示正常，并且视频也是可以播放的。但是在mip的预览页面显示不支持视频播放，手机也显示不支持

## 复现方式（线上bug 填写此项）
1. 手机型号：iphone6
2. 浏览器及版本：谷歌
3. 原页面url：https://mobile.51uyi.com/video/article/48493-160.html
4. mip预览页面url：https://www.mipengine.org/validator/preview/mip?title=MIP%20%E9%A2%84%E8%A7%88&ext=%7B%22url%22%3A%22https%3A%2F%2Fmobile.51uyi.com%2Fvideo%2Farticle%2F48493-160.html%22%7D

**Comment by pearlwang1106** [comment]
你的 video 的 url 是http的，在预览的时候有问题
