### ISSUE TITLE
页面中元素在预览页面不显示

### ISSUE THREAD

**Issue by JamesSky** [mipengine/mip-extensions#595]
## 问题分类
- [ x ] MIP-Cache下效果异常

## 问题描述
原页面中的dom元素正常显示，到了mip预览页面dom元素没有了

## 复现方式（线上bug 填写此项）

1. 原页面URL：https://mobile.51uyi.com/nanxing/
2. mip预览页面url：https://www.mipengine.org/validator/preview/mip?title=MIP%20%E9%A2%84%E8%A7%88&ext=%7B%22url%22%3A%22https%3A%2F%2Fmobile.51uyi.com%2Fnanxing%2F%22%7D

**Comment by pearlwang1106** [comment]
是 '.zh_info_header' 这个dom 吧，看你这里定义了样式 `position: fixed`, 这是不符合我们规范的，如果要用 fixed 定位，请使用我们的 [mip-fixed 组件](https://www.mipengine.org/doc/3-widget/3-customize-widget/fixed-widget.html)

**Comment by jennyliang220** [comment]
问题可参考 广告相关第三条 http://www.cnblogs.com/mipengine/p/mip_dev_faq.html
