### ISSUE TITLE
mip-semi-fixed 单词拼错了

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#616]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用

## 问题描述
mip-semi-fixed 单词拼错了
![image](https://cloud.githubusercontent.com/assets/8498677/26452200/b00e83ac-4191-11e7-9e1d-9278daea1274.png)

## 您的建议方案

mip-semi-fixed-fixedsatus -> mip-semi-fixed-fixedstatus

**Comment by pearlwang1106** [comment]
done
