### ISSUE TITLE
mip-ad 在同一个页面中不能复用

### ISSUE THREAD

**Issue by Jessica-zc** [mipengine/mip-extensions#627]
最近在做网站的MIP改版，因为涉及到联盟的收入。有多个模块会调用用一个广告位置。但是在测试的过程中发现同一个广告位在同一个页面中只显示一次

**Comment by pearlwang1106** [comment]
能给一个页面地址吗

**Comment by Jessica-zc** [comment]
现在是线下测试环境  我先放一个测试文档去线上吧
http://m.9939.com/miptext.html?ttttfffffhhhhh
百度联盟的广告代码
<mip-ad  type="baidu-wm-ext" domain="jsm.9939.com"  token="he3a1ecf95f2c9f031db137a98efa76ebc0cacde0b36"><div id="he3a1ecf95f2c9f031db137a98efa76ebc0cacde0b36"></div></mip-ad>

只在第一个列表中显示 下面的列表都不显示了

**Comment by Jessica-zc** [comment]
`<mip-ad  type="baidu-wm-ext" domain="jsm.9939.com"  token="he3a1ecf95f2c9f031db137a98efa76ebc0cacde0b36"><div id="he3a1ecf95f2c9f031db137a98efa76ebc0cacde0b36"></div></mip-ad>
`

**Comment by pearlwang1106** [comment]
你好，如果要在同一页面中展现多个广告，需要申请不同的广告位

**Comment by Jessica-zc** [comment]
好吧  这算是一个BUG么  后期会修改不？

**Comment by pearlwang1106** [comment]
这个是广告策略，不算bug哈
