### ISSUE TITLE
ssp投放代码的问题

### ISSUE THREAD

**Issue by regboy8** [mipengine/mip-extensions#635]
mip页面中使用：<mip-ad 
    type="ad-baidussp"
    sspId="xxx">
</mip-ad>
来调用ssp中的代码位，代码位中的物料是富媒体，结果mip中页面的展现出来时是通过iframe里来加载代码，而非直接在页面上附加富媒体的内容，请问能否改成跟ssp原生代码调用一样的效果？

**Comment by wupengFEX** [comment]
@regboy8 麻烦提供一个示例

**Comment by regboy8** [comment]
mip投放的效果：
https://m.ys137.com/test/ssp.htm
普通ssp代码投放的效果：
https://m.ys137.com/test/ssp_wap.htm

**Comment by wupengFEX** [comment]
@regboy8 在mip页里是会通过iframe的形式来加载，样式展现不同是css没加载导致的，你可以把css放在物料里进行加载

**Comment by regboy8** [comment]
@wupengFEX mip中只能通过iframe来加载啊？ssp原生的调用代码中好像没办法使用iframe来加载吧？这样的话我只能用2个不同的代码位来加载广告了，这样管理会比较麻烦

**Comment by wupengFEX** [comment]
ssp在mip页返回的就是带iframe的html
