### ISSUE TITLE
mip-infinitescroll 使用问题

### ISSUE THREAD

**Issue by RuningSnails** [mipengine/mip-extensions#636]
返回的josn数据严格按照官方{
    status: 0, 
    data: { 
        items: []
    }
}

  - status 0 表示请求成功
  - items: [] 是需要渲染的数据
返回，但是前台中如何输出呢，获取不到数据。

**Comment by wupengFEX** [comment]
@RuningSnails 数据由mip-infinitescroll自动根据data-src属性获取，且需要在mip-infinitescroll写template标签，用于渲染返回数据，可参照官网提供的[文档示例](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html)进行开发，如还有问题请附上示例页面。

**Comment by RuningSnails** [comment]
http://wap.leb13.com//mingxing/   这个为测试网页

**Comment by wupengFEX** [comment]
数据接口返回有问题，status返回的应该是一个number类型，并且items里面应该是一个对象，是你需要渲染模版的数据
```
{
    "status": "0",
    "data": {
        "items": "https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=242696669,3516394492&fm=80&w=179&h=119&img.JPEG"
    }
}
```

**Comment by bradenhan** [comment]
本地用测试数据json包，获取不到数据啊，报语法错误

**Comment by bradenhan** [comment]
http://wap.leb13.com//mingxing/  测试网页404

**Comment by wupengFEX** [comment]
#741

**Comment by momofan** [comment]
7月28日上线

**Comment by allen886** [comment]
我也遇到这个问题了，单独访问接口能访问到数据，而且跟官方要求的数据类型一致，但是template就是渲染不了数据 。把数据写死 下拉也显示不出来
