### ISSUE TITLE
mip使用问题

### ISSUE THREAD

**Issue by RuningSnails** [mipengine/mip-extensions#638]
mip该如何使用呢，文档中没有任何的demo，只有一个代码，完全抓瞎，不知道该添加到哪里，比如手势中  
示例
var util = require('util');
var Gesture = util.Gesture;
var customEle = require('customElemenet').create();

var build = function () {
    var gesture = new Gesture(this.element);

    // on 可接受多个事件名做为参数，以空格分隔。如 gesture.on('tap swipe')
    gesture.on('tap', function (event, data) {
        // 原始事件。如tap事件是通过 touchend 触发，event为tap对应的touchend事件对象
        console.log(event);
        // gesture 计算后的数据。参数介绍见后面
        console.log(data.type); // "tap"
    });
};

由于页面中不让放js标签，那么这段代码我该放在哪里呢。

**Comment by wupengFEX** [comment]
@RuningSnails 可以参考我们的 [组件示例平台](https://www.mipengine.org/doc/3-widget/10-widgets.html)，里面大部分组件都附加了demo，点击组件链接可供查看！
另外如果需要自定义js的话需要封装组件，这部分在[mip组件开发规范](https://www.mipengine.org/doc/2-tech/4-mip-widget.html)里有详细说明了

**Comment by GKrace** [comment]
请参考：[mip-sample.js](https://github.com/mipengine/mip-extensions/blob/master/mip-sample/mip-sample.js)
