### ISSUE TITLE
mip-link字体单位不合理

### ISSUE THREAD

**Issue by zhao-ping** [mipengine/mip-extensions#639]
mip-link会自己把链接的字体单位改成px,我用的是rem单位，改成px后，手机屏幕横屏时，样式就不合适了，个人觉得这样的设计不合理，请更正，谢谢！

**Comment by wupengFEX** [comment]
@zhao-ping 麻烦提供一个demo页面，我进一步看下

**Comment by momofan** [comment]
可以使用如下方案：<a data-type="mip" data-title="我是tilte" href="mipurl">我是一个 mip 的子链</a>。目前代码已上线，正在准备说明文档 @zhao-ping

**Comment by momofan** [comment]
可以使用如下方案：
```html
<a data-type="mip" data-title="我是title" href="mipurl">我是一个 mip 的子链</a>
```
。目前代码已上线，正在准备说明文档 @zhao-ping

**Comment by zhao-ping** [comment]
请问，这个需要接入类似mip-link这样的插件库吗？

**Comment by momofan** [comment]
不需要，这个不依赖组件 js @zhao-ping
