### ISSUE TITLE
mip-list组件中无限制调取接口数据

### ISSUE THREAD

**Issue by liuhen0806** [mipengine/mip-extensions#640]
mip-list组件：
异步请求的数据，已经显示加载完毕了，但是点击加载完毕还是会请求接口，希望当页面数据请求完毕后，不要在请求接口
![aaaaaaaa](https://user-images.githubusercontent.com/23732056/27122753-3f2ea7ce-511e-11e7-9462-89417d9cd22f.png)

**Comment by momofan** [comment]
@jennyliang220

**Comment by jennyliang220** [comment]
@liuhen0806 请按照issue模板来提issue，给出页面示例url。谢谢

**Comment by liuhen0806** [comment]
测试地址:http://m.120ask.com/shilu/bdinfo/0h8sflc4fitods69

**Comment by liuhen0806** [comment]
@jennyliang220 测试地址:http://m.120ask.com/shilu/bdinfo/0h8sflc4fitods69

**Comment by jennyliang220** [comment]
# mip-list 升级方案
### 问题原因
![image](https://user-images.githubusercontent.com/8498677/27224231-8b4c90c2-52c6-11e7-81f5-f1a0e020fc6c.png)
这个按钮具有on属性：on="tap:mip-list.more"。当文字内容变成“已经加载完毕”后，on属性仍然存在，导致点击仍然触发more操作，向后端发请求。

### 解决办法
当页面不再有新内容返回后，将class="mip-list-more showmore"的on属性制空，不再监听tap事件。

**Comment by jennyliang220** [comment]
6.22 已上线
