### ISSUE TITLE
mip-share 微信缩略图

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#646]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [mip-share ] MIP 组件使用

## 问题描述
icon 属性已经添加，通过微信圈浏览分析链接内容状态下，再分享新链接就不会显示图了。

## 您的建议方案

建议改善实现可以显示缩略图，提升客户使用体验

**Comment by dongshihao** [comment]
在微信(朋友圈)中打开的网页,点击页面内分享支持手百和QQ浏览器；点击右上角的微信分享需要依照微信API进行图片埋点.

**Comment by momofan** [comment]
已上线

**Comment by xiaojinping** [comment]
我们也想用这个组件，但是，在测试的时候，发现了一些问题，缩略图，只有分享到qq空间的时候，才有缩略图，其他的几种方式都不行，比如微信朋友圈，微信好友，qq，新浪微博，这几种方式都不行。我写了个测试用的demo:url === 
http://xiekun5.w0.testwz.cn/

**Comment by xiaojinping** [comment]
还有个事忘了说了，这个组件在微信里打开，朋友圈分享和微信分享是无效的，所以，我写的这个demo做了一定的处理，在微信上打开，是弹出一个提示，准备让用户去点击微信自带的分享功能，在除了qq和uc之外的浏览器里打开，也有个相应的提示。如果能实现在微信里打开也能分享就好了
