### ISSUE TITLE
CSS URL超文本链接颜色

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#647]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [CSS ] MIP 组件使用

## 问题描述
超文本链接显示是黑色，不够多元化，黑色背景网站根本看不清链接

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：http://m.kmgmy.com/news_info.asp?id=1924
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案

建议css 超文本链接颜色可以修改

**Comment by wupengFEX** [comment]
@lrvingyang 每个mip页的head标签中允许使用一个通过 mip-custom 属性标记的 style 标签，如：`<style mip-custom="mip-custom"></style>`，可以将自己的样式编译或直接写在里面

**Comment by lrvingyang** [comment]
好的，我试试！感谢
