### ISSUE TITLE
mip-gototop 显示高度

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#650]
mip-gototop 无法指定出现浮动的高度。

**Comment by momofan** [comment]
需求合理，接管开发

**Comment by jennyliang220** [comment]
https://www.mipengine.org/examples/mip-extensions/mip-gototop.html 组件已经存在这个功能，见文档示例-设置阈值。可以试试 threshold='1500' 。如果组件有兼容性问题，请按照issue模板提问，附上使用URL
