### ISSUE TITLE
mip-stats-baidu 在百度统计组件集成百度自动推送 

### ISSUE THREAD

**Issue by sy3tem** [mipengine/mip-extensions#653]
在组件内新增代码即可。
` var bp = document.createElement('script');
   bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';        
   var s = document.getElementsByTagName("script")[0];
   s.parentNode.insertBefore(bp, s);`

**Comment by momofan** [comment]
感谢反馈，我们这边先评估下需求，以及对应的实现方案

**Comment by momofan** [comment]
在跟进需求中
