### ISSUE TITLE
mip-list 组件在列表循环时进行条件判断

### ISSUE THREAD

**Issue by itodouble** [mipengine/mip-extensions#661]
## 问题分类
MIP 组件使用

## 问题描述
使用mip-list 列表组件
在列表中进行条件判断无法使用

`
<c:set var="type" value="{{type}}" ></c:set>
<c:out value="${type }" />
<c:if test="${type eq 2}">交流</c:if>
<c:if test="${type eq 1}">加盟评价</c:if>
<c:if test="${type eq 4}">消费评价</c:if>
<c:if test="${type eq 3}">投票</c:if>
`
在列表循环时 <c:out>可以输出值 <c:if test/>无用

**Comment by pearlwang1106** [comment]
mip 中采用的前端模板是 mustache，我本地测试 <c:out> 也不能输出
