### ISSUE TITLE
MIP不存在倒计时的组件

### ISSUE THREAD

**Issue by zhao-ping** [mipengine/mip-extensions#668]
**1.希望增加倒计时组件**
结合mip-list组件一起，倒计时完成时处罚ajax请求，完成list渲染。
**2.希望增加循环倒计时的功能**
比如每隔十分钟触发一次ajax请求，渲染list。
能够根据请求返回来的结果执行相应的操作。

**Comment by pearlwang1106** [comment]
能说一下 需求背景么

**Comment by zhao-ping** [comment]
比如彩票开奖10分钟一次的，而且，请求回来后并不一定开奖了，需要根据数据判断是否继续请求
而且直接用setINterval倒计时并不准确，需要修正时间

**Comment by pearlwang1106** [comment]
有示例页面吗，我想看下是否适合用mip-list

**Comment by zhao-ping** [comment]
请点链接查看，想要把这个做成MIP的
[https://tv.niu.cn/hb11x5/q3_zx.aspx](url)

**Comment by pearlwang1106** [comment]
同一个页面，不能一部分是mip，一部分不是

页面效果复杂可以反馈下是如何复杂，我们看看改造过程如何解决

**Comment by jennyliang220** [comment]
@momofan 写一下详细方案

**Comment by wupengFEX** [comment]
综合考虑，短期内倒计时组件不会被纳入开发计划中，如果有需求可以封装自定义组件！ @zhao-ping
