### ISSUE TITLE
组件链接代码被更改的问题

### ISSUE THREAD

**Issue by byqiqi** [mipengine/mip-extensions#674]
https://mipcache.bdstatic.com/static/v1/mip-html-ajax/mip-html-ajax.js
![image](https://user-images.githubusercontent.com/23182363/27521812-6c8af162-5a53-11e7-9284-ccbf33b90060.png)
改成这样也没意见，但要保证能正常使用啊
在HTTPS下（https://m.baidu.com/mip/c/***）
组件无法加载。
也不止这一个组件这样，很多都有这个问题。
![image](https://user-images.githubusercontent.com/23182363/27521847-b347b234-5a53-11e7-87bd-6077e0de8504.png)

**Comment by wupengFEX** [comment]
MIP 下的外链 js 是规定需要使用https协议的，否则不能直接使用

**Comment by byqiqi** [comment]
https://mipcache.bdstatic.com/static/v1/mip-html-ajax/mip-html-ajax.js
这链接，看第一张图，这是你们链接，固定成http，这又不是我能改的。
就是组件链接里的代码有时候都被转换了。

**Comment by wupengFEX** [comment]
mip组件上线之后生成的都是https协议的地址。你所提供的 URL 里我没有找到var d = 'https://mipserver.bdstatic.com/static/v1/mip-html-ajax/mip-html-ajax.js'这段代码，这并不是mip生成的地址，同时我们组件上线之后都是以https://mipcache.bdstatic.com为域名的，如果有你所提到的问题烦请提供具体URL地址，感谢！

**Comment by byqiqi** [comment]
@wupengFEX 
不是所有时候都这样，这是我昨天看到的时候截的图。
![default](https://user-images.githubusercontent.com/23182363/27536507-1e4ad3a6-5aa2-11e7-836d-ecf1e1efb312.png)

**Comment by byqiqi** [comment]
https://mipcache.bdstatic.com/static/v1/mip-html-os/mip-html-os.js

**Comment by byqiqi** [comment]
不知道你们这是弄的什么策略，但至少要让组件能正常加载才行啊。
在站长平台也反馈了，但没人回复。

**Comment by wupengFEX** [comment]
补充说明下，这块很有可能是劫持导致的，目前会把 cdn 的回原切换成 https，预计本周上线完成。上线后麻烦 @byqiqi 再帮忙确认，如果还有类似问题请提交issue！

**Comment by byqiqi** [comment]
@wupengFEX 
近期没发现这个问题了。
