### ISSUE TITLE
mip-sidebar滚动时出现bug

### ISSUE THREAD

**Issue by zhao-ping** [mipengine/mip-extensions#678]
页面内容很长时，tap事件，调出侧边栏后，滚动页面，页面的主体内容会滚动。
建议侧边栏调出来后页面主体部分禁止滚动
图片上传不了，但是，按照上面所说的，应该可以理解是怎么状态吧

**Comment by zhao-ping** [comment]
请问下，这个问题有没有去解决？
滚动侧边栏时，页面主题内容会滚动，这个会导致另外一个BUG。
在浏览器中打开时，侧边栏滚动到底部然后惯性的继续向上滚动时，会导致页面主体内容滚动，主题内容滚动会导致浏览器隐藏，页面高度会变高，侧边栏此时高度不是100%，侧边栏下面会露出一截。

**Comment by momofan** [comment]
开发中

**Comment by jennyliang220** [comment]
调研AMP和百度百科的用法，都是在侧边栏弹出时，禁止body或html的滚动。

**Comment by zhao-ping** [comment]
@jennyliang220 
请问这个问题是解决了吗？为啥我们的页面调出侧边栏后还是有这样子的问题
请查看链接：点击按钮（更多）时，调出侧边栏，滚动到底部后页面主体内容会滚动
[m.cz89.com](m.cz89.com)
