### ISSUE TITLE
建议添加类似require text的功能

### ISSUE THREAD

**Issue by elang126** [mipengine/mip-extensions#68]
在开发自有业务组件过程中，有时会有大量的DOM，希望能支持require html文件，把DOM结构模块化。

**Comment by jennyliang220** [comment]
require功能可以在开发的时候使用，通过脚手架工具编译，生成能够通过MIP校验的最终页面。比如使用fis的lnline功能 http://fis.baidu.com/fis3/docs/user-dev/inline.html
