### ISSUE TITLE
MIP Validator 检测工具，应包含 template 的语法，望解决。

### ISSUE THREAD

**Issue by hnzhangyang** [mipengine/mip-extensions#682]
MIP Validator 检测工具，应包含 template 的语法，望解决。
![qq 20170628140105](https://user-images.githubusercontent.com/20033699/27622500-131a26e4-5c0a-11e7-8486-3d10fdcd0755.png)

**Comment by wupengFEX** [comment]
@hnzhangyang 该校验功能官方开发完成，预计会在7月初上线！

**Comment by dongshihao** [comment]
校验于`2017-08-01`上线升级完毕。
