### ISSUE TITLE
MIP-Form 组件提交的话可否不弹出新页面

### ISSUE THREAD

**Issue by bradenhan** [mipengine/mip-extensions#683]
## 问题分类 
- [x] MIP - Form 组件使用 

## 问题描述
MIP-Form组件，提交的时候会弹出新页面，是否可以避免这个问题？求助

**Comment by bradenhan** [comment]
![default](https://user-images.githubusercontent.com/1844838/27669498-94e4adc0-5cb9-11e7-96b4-ca6b3bdfe4c2.png)
不知道可否把 form的target属性去掉

**Comment by bradenhan** [comment]
![default](https://user-images.githubusercontent.com/1844838/27669605-346732e6-5cba-11e7-8e10-278ddd7c6f1d.png)
不知道可否不带着属性。

**Comment by momofan** [comment]
get 可以去掉_blank
post 必需_blank,因为在 iframe 下面，无法跳出 iframe，存在问题。
方案讨论中

**Comment by wupengFEX** [comment]
@bradenhan  已上线，iframe里允许_blank和_top(非_blank的target属性都会解析为_top)两种方式，非iframe里无限制

**Comment by momofan** [comment]
已上线
