### ISSUE TITLE
提交组件失败

### ISSUE THREAD

**Issue by yanpanxiang** [mipengine/mip-extensions#685]
上传组件提示找不到mip组件目录，求解。

**Comment by wupengFEX** [comment]
@yanpanxiang 请提供下组件结构和package.json内容截图

**Comment by yanpanxiang** [comment]
body { line-height: 1.5; }blockquote { margin-top: 0px; margin-bottom: 0px; margin-left: 0.5em; }div.foxdiv20170703173703586671 { }body { font-size: 10.5pt; font-family: 'Microsoft YaHei UI'; color: rgb(0, 0, 0); line-height: 1.5; }

**Comment by wupengFEX** [comment]
由于压缩后没有包裹一层组件目录导致。同时我们也会修改官方博客中[组件压缩说明](http://www.cnblogs.com/mipengine/p/extension_platform.html)，让开发者能够更容易理解！

**Comment by wupengFEX** [comment]
@yanpanxiang [文档](http://www.cnblogs.com/mipengine/p/extension_platform.html)已更新！
