### ISSUE TITLE
mip-sidebar 侧边栏 安卓无法使用

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#687]
## 问题描述
mip-sidebar 侧边栏组件，安卓系统百度搜索APP 内打开网站，mip-sidebar 菜单无法弹出！

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by wupengFEX** [comment]
@lrvingyang 麻烦提供能够浮现问题的URL

**Comment by wupengFEX** [comment]
问题已上线，请查看线上效果

**Comment by lrvingyang** [comment]
辛苦了！
