### ISSUE TITLE
在MIP页中使用登陆（ cookie）

### ISSUE THREAD

**Issue by hnzhangyang** [mipengine/mip-extensions#693]
现有一个登陆插件需使用 cookie 来判断用户登录状态，获取用户头像等登陆信息。在使用组件平台提交组件的时候被告知需到此来提 issue，请问是什么情况？

**Comment by wupengFEX** [comment]
@hnzhangyang 请看下官方access 组件所提供的[登陆功能](http://www.cnblogs.com/mipengine/p/mip-access.html)是否适用与你的需求？

**Comment by hnzhangyang** [comment]
这个看过了，不满足，我们不需要权限设置，只需要读取 cookie 获得用户登录信息

**Comment by jennyliang220** [comment]
@wupengFEX 细化一下现有access的demo吧，只给出登录按钮 -》登录页面 -》登录成功的示例

**Comment by wupengFEX** [comment]
#699

**Comment by zhangmengcheng** [comment]
mip怎么设置cookie和获取cookie?

**Comment by wupengFEX** [comment]
@zhangmengcheng 可以参考[官方文档](https://www.mipengine.org/doc/3-widget/6-help/6-storage.html)，使用localstorage或者站点管理存储的方案
