### ISSUE TITLE
MIP组件审核平台审核插件mip-zpm-jobdetail被打回

### ISSUE THREAD

**Issue by wangjx90** [mipengine/mip-extensions#699]
由于组件使用了特殊【登录】和【cookie】功能，请到github 提交 issue， 详细描述您的功能和需求: https://github.com/mipengine/mip-extensions/issues 我们会有技术同学专门解答您的问题
请帮忙，谢谢

**Comment by jennyliang220** [comment]
1. 提issue前请搜索是否有类似issue存在，比如 #693 
2. 请看下官方[access 组件](http://www.cnblogs.com/mipengine/p/mip-access.html)所提供的登陆功能是否适用与你的需求？

**Comment by wangjx90** [comment]
看过了，和#693的情况差不多，只是用cookie获取用户登录的信息。access 组件不适用
