### ISSUE TITLE
组件失效

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#702]
iphone6 系统10.3.1 系统下
1、mip-gototop
2、mip-share

两个组件不显示！

iphone6S Plaus 、安卓、显示正常

**Comment by lrvingyang** [comment]
环境safari浏览器下！

**Comment by jennyliang220** [comment]
请按照模板提issue。麻烦给出页面的url

**Comment by lrvingyang** [comment]
mip-share 问题已经解决！

链接地址：m.kmgmy.com
![img_4642](https://user-images.githubusercontent.com/29472411/27899607-809a4880-625d-11e7-916e-b20b0cc01adf.jpg)

**Comment by jennyliang220** [comment]
@lrvingyang 能说一下当时为什么不显示，后来怎么解决的么？以后如果有开发者遇到类似问题，可以给他们提供解决办法

**Comment by lrvingyang** [comment]
一直没有解决！ 这问题依然存在

**Comment by jennyliang220** [comment]
![image](https://user-images.githubusercontent.com/8498677/28104837-8a34fb90-670f-11e7-95a7-bdc9b0d2f090.png)
现在问题解决了没有？

**Comment by lrvingyang** [comment]
现在已经解决！
