### ISSUE TITLE
mip-img标签宽度兼容问题

### ISSUE THREAD

**Issue by NokeyKing** [mipengine/mip-extensions#703]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [x] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-img标签的图片在全屏范围内按图片原有比例显示，即宽到达100%时宽度显示100%上下留白，高度到达100%时高度100%左右留白，ios的浏览器没有问题，安卓手机的UC浏览器存在兼容问题，表现是宽度一直显示100%导致图片变形

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by bradenhan** [comment]
mip-img标签的图片在全屏范围内按图片原有比例显示，即宽到达100%时宽度显示100%上下留白，高度到达100%时高度100%左右留白，ios的浏览器没有问题，安卓手机的UC浏览器存在兼容问题，表现是宽度一直显示100%导致图片变形

**Comment by jennyliang220** [comment]
存在相同问题 #705 ，可以到那个issue中补充一下url
