### ISSUE TITLE
mip-img标签在安卓系统的UC和QQ浏览器下面宽度兼容问题

### ISSUE THREAD

**Issue by bradenhan** [mipengine/mip-extensions#705]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-img标签的图片在全屏范围内按图片原有比例显示，
即宽到达100%时宽度显示100%上下留白，
高度到达100%时高度100%左右留白，
ios的浏览器没有问题，
安卓手机的UC浏览器存在兼容问题，
表现是宽度一直显示100%导致图片变形

## 复现方式（线上bug 填写此项）
1. 手机型号：华为、小米等
2. 系统版本：安卓系统
3. 浏览器及版本：UC（V1.5.8.945）、QQ浏览器（7.6.1.3350）
4. 页面URL：暂无
5. 复现操作：

**Comment by jennyliang220** [comment]
请给出一个页面URL，方便根据实际情况我们追查问题

**Comment by bradenhan** [comment]
http://bradenhan.tech/fn-comment/demo5.html

**Comment by bradenhan** [comment]
http://bradenhan.tech/fn-comment/demo3.html

**Comment by NokeyKing** [comment]
还没有解决呢~期待结果

**Comment by momofan** [comment]
目前我们这边已经复现，问题已经在跟进定位中，多谢反馈，有进展会及时同步

**Comment by dongshihao** [comment]
@NokeyKing 可以尝试以下修复方案：
1、设置最小宽度
`img.mip-fill-content{
    min-width: 0;
}`
2、组件修改布局方式
`layout="container"`

**Comment by NokeyKing** [comment]
@dongshihao 多谢反馈，问题已搞定

**Comment by dongshihao** [comment]
好的 多谢对MIP的关注和支持！

**Comment by momofan** [comment]
已解决
