### ISSUE TITLE
经过测试 mip-showmore组件不支持嵌套功能，如果是使用方法不对，能否补充如何使用嵌套文档~

### ISSUE THREAD

**Issue by jiangzhuorong** [mipengine/mip-extensions#715]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
在问题列表里有一个showmore，而在每个问题里面还会有一个showmore，使用showmore嵌套时外层showmore会默认选择最近的showmorebtn，也就是问题列表里面第一个问题里面的showmorebtn。

## 需求描述（新需求 填写此项）
1. 效果页面URL： http://ask.39.net/html5/mip/showmore-test.html
2. 效果描述:

## 您的建议方案
showmore组件支持嵌套功能以适应使用场景

**Comment by dongshihao** [comment]
组件BUG，正在修复~
