### ISSUE TITLE
mip-stats-baidu 支持 _setPageTag 接口

### ISSUE THREAD

**Issue by firedfox** [mipengine/mip-extensions#717]
## 需求描述（新需求 填写此项）

mip-stats-baidu 支持 _setPageTag 接口

## 您的建议方案

我们会尽快提交一个PR

**Comment by dongshihao** [comment]
具体是个什么接口呢？ 把功能和需求描述详细。

**Comment by dongshihao** [comment]
和相关同学联系，已满足需求，关闭本issue。
