### ISSUE TITLE
mip-stats-baidu 百度主动推送

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#722]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ mip-stats-baidu ] MIP 组件使用

## 问题描述
请问 mip-stats-baidu 百度统计组件现在集成百度自动推送了吗？

**Comment by momofan** [comment]
经和百度统计同事的沟通，百度统计目前暂未支持百度自动推送功能，所以，您 issue 提的问题，建议先线下详细沟通一下，qq：3020128386。谢谢

**Comment by momofan** [comment]
@lrvingyang http://tieba.baidu.com/p/4168875553 确认一下，是指这个帖子里面的功能吗？

**Comment by lrvingyang** [comment]
对！

**Comment by dongshihao** [comment]
#653  我们正在跟进中~

**Comment by momofan** [comment]
@lrvingyang 和百度统计同事确认，这个是默认支持的，有百度推送的功能
