### ISSUE TITLE
mip-stats-baidu 的 API 语义化

### ISSUE THREAD

**Issue by junmer** [mipengine/mip-extensions#723]
## 问题分类

- [x] MIP 组件使用
- [ ] MIP-Cache下效果异常
- [ ] MIP 页面不通过校验
- [ ] MIP 页面内容（广告不显示，排版错乱）

## 问题描述

 对 [百度统计的 JS-API](http://tongji.baidu.com/open/api/more?p=ref_trackPageview) 的实现，当前组件定义如下

> setconfig值必须encodeURIComponent处理,如[_setAutoPageview, true]需转化为%5B_setAutoPageview%2C%20false%5D字符串传递 

坦率的说，不够好用
- 要先 encodeURIComponent 不能直接写码
- 不支持设置多个参数
- API 没有语义化，没用过 百度统计的童鞋 ，不知道能干啥

## 您的建议方案

-  无需 encodeURIComponent
- API 外漏
- 标签可以写多个，添加写

demo:

```html
<mip-stats-baidu token="{%$token%}"></mip-stats-baidu>
<mip-stats-baidu trackPageview="{%$pageURL%}"></mip-stats-baidu>
<mip-stats-baidu trackEvent="['music', 'play', 'Hey Jude']"></mip-stats-baidu>
<mip-stats-baidu setCustomVar="[1, 'login', '1', 2]"></mip-stats-baidu>
<mip-stats-baidu setAccount="{%$Account%}"></mip-stats-baidu>
<mip-stats-baidu setAutoPageview="false"></mip-stats-baidu>
```

**Comment by dongshihao** [comment]
目前的setconfig不支持设置多组参数，API隐藏，对开发者不友好。
计划改成参数配置的形式，并且API外露,如下形式：
```javascript
<mip-custom>
    <script type="application/json">
        {
            'token': '02890d4a309827eb62bc3335b2b28f7f',
            '_setCustomVar': 'index, name, value, opt_scope'
        }
    </script>
</mip-custom>
```

**Comment by dongshihao** [comment]
已上线
