### ISSUE TITLE
mip-showmore 组件增加动画

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#738]
## 问题分类

（请在括号中输入"x"来选择）
- [X] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-showmore 组件增加动画

**Comment by momofan** [comment]
7月27日 提测

**Comment by jennyliang220** [comment]
#762 上线
