### ISSUE TITLE
mip-form组件是否可以不填写url和method

### ISSUE THREAD

**Issue by wangjx90** [mipengine/mip-extensions#750]
## 问题分类

（请在括号中输入"x"来选择）
- [X] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
让用户在input输入框输入内容，在本页面中进行业务操作。所以form表单不需要url跳转也不需要设置method方式。

## 您的建议方案
希望mip-form组件可以不填写url和method

**Comment by dongshihao** [comment]
你是想接管form的submit吗？
MIP项目组正在计划升级mip-form组件，时间待定。

**Comment by wupengFEX** [comment]
@wangjx90 请描述详细的业务场景，或提供使用场景下的页面地址

**Comment by wangjx90** [comment]
搜索结果页，根据用户在input框中的内容在页面中进行搜索。所以form表单不需要url也不需要设置method方式。业务场景就是这样

**Comment by momofan** [comment]
建议采用 form 的标准跳法，action:  http://mip.zhaopin.com/searchjob/search     参数：KeyWord=123&Location=736  method: GET     如果城市code信息 拿不到的化，可以写个组件去异步拿一下，或者直接后端识别，通过 php等直接输出到页面里面，或者存到 cookie 里面 都是可以的。
