### ISSUE TITLE
MIP百度搜索结果问题。

### ISSUE THREAD

**Issue by byqiqi** [mipengine/mip-extensions#751]
手机百度APP上搜索“天天酷跑破解版”
**问题1：**
![20170728_172315](https://user-images.githubusercontent.com/23182363/28711362-f984313a-73b9-11e7-8465-1cda04f5666b.png)
这条结果，点击弹出证书问题。
![screenshot_20170728-172037](https://user-images.githubusercontent.com/23182363/28711488-4b8f5220-73ba-11e7-8835-7e14c8171ed7.png)
![screenshot_20170728-172057](https://user-images.githubusercontent.com/23182363/28711496-520ca724-73ba-11e7-8733-83cd80a9c4c9.png)

**问题2：**
![image](https://user-images.githubusercontent.com/23182363/28711523-6e5841a4-73ba-11e7-8906-fad9fc7b4ba6.png)
这结果点进去是被转码的，显示不正常。
这是MIP原页面：http://m.hackhome.com/Mipx/SoftView_339387.html
[http://m.baidu.com/from=0/bd_page_type=1/ssid=0/uid=0/pu=usm%403%2Csz%401320_1001%2Cta%40iphone_2_4.4_3_537/baiduid=76A38B6573A5A8175D950CED21053EE4/w=0_10_/t=iphone/l=3/tc?ref=www_iphone&lid=11055526803944483782&order=5&fm=alop&waplogo=1&cyc=1&h5ad=1&srd=1&dict=32&mip2h5=1&tj=www_normal_5_0_10_title&vit=osres&waput=1&cltj=normal_title&asres=1&nt=wnor&title=%E5%A4%A9%E5%A4%A9%E9%85%B7%E8%B7%911.0.31%E7%A0%B4%E8%A7%A3%E7%89%88%E4%B8%8B%E8%BD%BD%2C%E5%A4%A9%E5%A4%A9%E9%85%B7%E8%B7%911.0.31%E5%86%85%E8%B4%AD%E7%A0%B4%E8%A7%A3%E7%89%88...&w_qd=IlPT2AEptyoA_yk57Acc8um6GlJPhZEp-k1NcerTyx_&sec=22809&di=b8ad23db89dbdec1&bdenc=1&nsrc=IlPT2AEptyoA_yixCFOxXnANedT62v3IGtiNNCtP_jWzmI39h47aUbBHWy4n2Sm51EbvsJSHh2hew8Oi0G9l6so4g43](http://m.baidu.com/from=0/bd_page_type=1/ssid=0/uid=0/pu=usm%403%2Csz%401320_1001%2Cta%40iphone_2_4.4_3_537/baiduid=76A38B6573A5A8175D950CED21053EE4/w=0_10_/t=iphone/l=3/tc?ref=www_iphone&lid=11055526803944483782&order=5&fm=alop&waplogo=1&cyc=1&h5ad=1&srd=1&dict=32&mip2h5=1&tj=www_normal_5_0_10_title&vit=osres&waput=1&cltj=normal_title&asres=1&nt=wnor&title=%E5%A4%A9%E5%A4%A9%E9%85%B7%E8%B7%911.0.31%E7%A0%B4%E8%A7%A3%E7%89%88%E4%B8%8B%E8%BD%BD%2C%E5%A4%A9%E5%A4%A9%E9%85%B7%E8%B7%911.0.31%E5%86%85%E8%B4%AD%E7%A0%B4%E8%A7%A3%E7%89%88...&w_qd=IlPT2AEptyoA_yk57Acc8um6GlJPhZEp-k1NcerTyx_&sec=22809&di=b8ad23db89dbdec1&bdenc=1&nsrc=IlPT2AEptyoA_yixCFOxXnANedT62v3IGtiNNCtP_jWzmI39h47aUbBHWy4n2Sm51EbvsJSHh2hew8Oi0G9l6so4g43)
![image](https://user-images.githubusercontent.com/23182363/28711651-e164ddd8-73ba-11e7-875c-05761c871c11.png)
被转码的代码。

**Comment by jennyliang220** [comment]
第一个问题，transcoder页面不是https的，按说不应该报证书问题。麻烦提供下手机型号，浏览器名称及版本。

**Comment by jennyliang220** [comment]
问题收到，定位中

**Comment by jennyliang220** [comment]
1. 证书问题是由转码本身引起的，我们已经联系百度同事修复。
2. 页面被转码的原因可以参见博客[MIP问题解决方案大全](http://www.cnblogs.com/mipengine/p/mip-faqs.html) - 问题4.7
![image](https://user-images.githubusercontent.com/8498677/28867380-89a1de24-77a8-11e7-9c77-942e04b84164.png)
