### ISSUE TITLE
mip-accordion折叠组件展示问题

### ISSUE THREAD

**Issue by liuhen0806** [mipengine/mip-extensions#753]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip2.0里面使用了折叠组件，如果手机屏幕比较小的话， 问答的回复没折叠 ，当折叠组件进入可视化区域，就执行了  页面会闪一下 接着页面隐藏了；折叠组件没在第一屏露出来  当我想下滑动的时候（快一点）  下面的回复还没来得及 折叠 ，等一下页面会收起 ， 这个时候 页面会闪一下。

## 复现方式（线上bug 填写此项）
1. 手机型号：iphone6 或者 谷歌模拟 iphone 6 或者 iphone5
2. 系统版本：
3. 浏览器及版本：safari浏览器
4. 页面URL：https://m.120ask.com/askg/mip_detail/13416454
5. 复现操作：
使用iphone6，访问url，折叠组件没在第一屏露出来  当我想下滑动的时候（快一点）  下面的回复还没来得及 折叠 ，等一下页面会收起 ， 这个时候 页面会闪一下。

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
组件修改，不要出现页面闪一下的问题

**Comment by jennyliang220** [comment]
### 问题定位
组件初始化写在生命周期的firstInviewCallback中了，造成组件滑动进入页面后初始化。

### 解决方案
修改组件初始化时机，当build时触发。

**Comment by jennyliang220** [comment]
在[mip-accordion文档](https://www.mipengine.org/examples/mip-extensions/mip-accordion.html)中增加了说明:
提示：页面加载初默认隐藏的节点，需要添加 class="mip-accordion-content"。
