### ISSUE TITLE
关于mip组件不能使用cookie的问题。

### ISSUE THREAD

**Issue by deiphi** [mipengine/mip-extensions#754]
## 组件使用了cookie被驳回

我开发了一个广告组件，里面使用了cookie保存客户端的ip地址，以免重复请求提高性能(cookie过期时间是一天)，用于地区定向投放广告。如果不使用cookie还是别的方式吗？

**Comment by jennyliang220** [comment]
组件名：mip-fdad

**Comment by wupengFEX** [comment]
@deiphi  cookie使用API计划在 mip 二级域名全量后进行开发，二级域名预计能在半个月后全量。目前你可以使用我们提供的[存储方案](https://github.com/mipengine/mip-blog/blob/master/01_MIP%E5%AD%98%E5%82%A8.md)的其他方式进行存储管理

**Comment by deiphi** [comment]
OK，谢谢！@wupengFEX
