### ISSUE TITLE
mip-stats-baidu 统计跳出率过高

### ISSUE THREAD

**Issue by dongshihao** [mipengine/mip-extensions#758]
## 问题分类
- [x] MIP 组件BUG
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
这边接到一个用户的反馈，是关于mip页的百度统计跳出率高
case是
这个网站的典型页面
http://m.27yx.com/book/125.html
http://m.27yx.com/book/125/39887.html

<img width="1114" alt="baidu-sta" src="https://user-images.githubusercontent.com/6845419/28902497-c4b125b8-7831-11e7-80ab-e5228610d7ad.png">

## 需求描述（新需求 填写此项）
1. 协助查明原因 
2. 给出解决方案

**Comment by dongshihao** [comment]
mip-stats-baidu组件的问题：
1、结果页点进着陆页，统计请求中su参数错误的取了着陆页的url，应该取上一个页面(referer)，也就是大搜结果页的url。
![image](https://user-images.githubusercontent.com/6845419/28902540-20a40b24-7832-11e7-8073-5056eda7a6a8.png)
2、着陆页之后的用户访问，su参数取的仍然是当前页面的url，而且错误的带了eqid。
3、百度统计根据`host`和`eqid`分割日志；因为着陆页和着陆页之后的su参数都带的当前url，而且mip页下的url是m.baidu.com下的，且带了eqid，别误认为是大搜来源，所以被错误的分割了。

解决方案：
mip-stats-baidu组件改造，着陆页和二级页面`su`参数改为referer地址，二级页跳转参数移除eqid。

**Comment by dongshihao** [comment]
#723

**Comment by jennyliang220** [comment]
百度统计跳出率高的问题仍在个别网站存在。需要@dongshihao关注下：
![image](https://user-images.githubusercontent.com/8498677/31760791-781df362-b47b-11e7-98fb-b9c3f7913203.png)
