### ISSUE TITLE
组件中使用到cookie被拒绝

### ISSUE THREAD

**Issue by wangzh1010** [mipengine/mip-extensions#760]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-chinacn-search组件和mip-chinacn-filter组件。
搜索或过滤时需要使用cookie先存储一些数据。提供的[存储方案](https://github.com/mipengine/mip-blog/blob/master/01_MIP%E5%AD%98%E5%82%A8.md)中，站长管理存储是否可以满足需求？

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by jennyliang220** [comment]
可以使用使用[存储方案](https://github.com/mipengine/mip-blog/blob/master/01_MIP%E5%AD%98%E5%82%A8.md)么？
