### ISSUE TITLE
mip-stats-cnzz怎么使用？

### ISSUE THREAD

**Issue by JefferyZh** [mipengine/mip-extensions#774]
## 问题分类

- [ x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-stats-cnzz怎么使用？没有说明呢？

**Comment by momofan** [comment]
一、mip 页需要添加的信息：
1、脚本：
<script src="https://mipcache.bdstatic.com/static/v1/mip-stats-cnzz/mip-stats-cnzz.js"></script>

2、mip 页body 下添加 html：
<mip-stats-cnzz token="你的 cnzz site id"></mip-stats-cnzz> 
token 为站长的站点在友盟（cnzz）上接入申请的唯一 ID。
添加 cnzz 的线上脚本
<script src="https://mipcache.bdstatic.com/static/v1/mip-stats-cnzz/mip-stats-cnzz.js"></script>

3. cnzz统计事件追踪

<mip-stats-cnzz token="你的 cnzz site id" setconfig="全局配置"></mip-stats-bidu>

需要触发事件追踪的dom
<div data-stats-cnzz-obj="
%7B%22type%22:%22click%22,%22data%22:%22%5B_trackPageview,%20/virtual/login%5D%22%7D
">
  事件追踪dom
</div>

setconfig配置属性说明:
一些需要全局的属性如: setconfig:[_setAutoPageview, true]

data-stats-cnzz-obj配置属性说明:
如：data-stats-cnzz-obj:{"type":"触发机制(click点击触发/load为页面加载自动触发)","data":"[_trackPageview, /virtual/login]"}

setconfig与data-stats-cnzz-obj均需要encodeURIComponent转码后传入


二、mip 页使用 mip cache接入需要考虑：
 由于使用 mip cache 后，域名会相应的做调整，需要在CNZZ 上添加统计域名：mipcache.bdstatic.com。（注意：近期在启动域名升级，参看
 http://www.cnblogs.com/mipengine/p/MIPCache_update.html）  否则 PV会被过滤掉
 
![image](https://user-images.githubusercontent.com/3773790/29401891-8592aa84-8365-11e7-991a-f32da4eed645.png)

  
附录：
 1、mip cache 说明文档
 2、mip cache 域名替换规则（注意：近期在启动域名升级，参看
 http://www.cnblogs.com/mipengine/p/MIPCache_update.html）  
    原域名url  ——>   https://mipcache.bdstatic.com/c/原域名url
例如：http://china.huanqiu.com/article/2016-07/9232054.html
           转换后 https://mipcache.bdstatic.com/c/china.huanqiu.com/article/2016-07/9232054.html

**Comment by Jeffiy** [comment]
token 放哪里的？

**Comment by dongshihao** [comment]
挂载到标签上，组件会自动获取并带到请求中，如下：
`<mip-stats-cnzz token="">`

因为一些历史原因，这个组件没有详细的`README`；我们将会详细补充。

**Comment by JefferyZh** [comment]
https://github.com/mipengine/mip-extensions/tree/master/mip-stats-cnzz  还是没有说明哦

**Comment by dongshihao** [comment]
mip-stats-cnzz组件暂时还没有增加详细文档的计划，有任何问题通过issue沟通和处理。

**Comment by xiaojinping** [comment]
我在使用mip-stats-cnzz时，发现cnzz内部的script.src="s11",而我的是s13;
<mip-stats-cnzz token="cnzz_stat_icon_1270258898" class="mip-element mip-layout-container"><script language="JavaScript" src="https://s11.cnzz.com/z_stat.php?id=cnzz_stat_icon_1270258898&amp;web_id=cnzz_stat_icon_1270258898"></script></mip-stats-cnzz>
实际小，正确的src应该是https://s13.cnzz.com/z_stat.php

**Comment by xiaojinping** [comment]
cnzz里的这个src不应该固定成一个s11，应该是一个灵活的src地址，他有可能是s11,也可能是s13,也有可能是s19
