### ISSUE TITLE
有没有倒计时跳转的，比如说一个错误页，5秒后进行跳转到首页

### ISSUE THREAD

**Issue by orgxixi** [mipengine/mip-extensions#779]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
有没有倒计时跳转的，比如说一个错误页，5秒后进行跳转到首页

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by momofan** [comment]
<meta http-equiv="refresh" content="5; url=http://www.youwebsite.com/" />  直接用 meta 是否能解决问题呢? @orgxixi

**Comment by orgxixi** [comment]
不能，页面需要显示有倒计时的提示，然后进行跳转
