### ISSUE TITLE
完善mip-filter 筛选组件问题2

### ISSUE THREAD

**Issue by Micor228** [mipengine/mip-extensions#796]
问题分类

（请在括号中输入"x"来选择）

[ x] MIP 组件使用
 MIP 页面内容（广告不显示，排版错乱）
 MIP 页面不通过校验
 MIP-Cache下效果异常
问题描述

筛选组件依然不够灵活，有时筛选标题的子项(filter-link)为了美观，我们会在标题前添加小图标，但筛选的结果永远都是子项里的文本，无法连同前面的小图标带出到筛选结果中！（2017-8.25）

需求描述（新需求 填写此项）

筛选的结果永远都只是子项里的文本，我认为筛选结果应为筛选子项里的所有内容（除了带filter-num类的span以外）

例如：视频站的视频源，每个视频源都会有对应的小图标，而筛选结果就只有视频源的名称了（没了子项里的图标），相当丑陋！

您的建议方案

筛选结果应为筛选子项里的所有内容（除了带filter-num类的span以外），或者开发者是否有更为灵活的方法。

**Comment by jennyliang220** [comment]
可以修改mip-filter后提交pull request。只要向前兼容即可。
