### ISSUE TITLE
表单提交为什么要限制password?

### ISSUE THREAD

**Issue by zhangmengcheng** [mipengine/mip-extensions#798]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
如果吧表单提交password取消这样很不安全相对于企业网站

**Comment by zhangmengcheng** [comment]
如果可以请开发password

**Comment by dongshihao** [comment]
经过验证：MIP 校验和预览平台没有对`<input type="password" />`进行限制；`password` 类型的`input`会被正常渲染。
请问你遇到的**限制password**的情况是怎么样的，详细给出实例，我们好一起帮你追查。

**Comment by zhangmengcheng** [comment]
我说的限制是填写密码时都是明文了，当时可能我没说清楚不号意思，明文的填写密码应该对我们来说不太合适

**Comment by dongshihao** [comment]
我这边没复现这个问题，如下DEMO：
[mip-form password DEMO](https://jsfiddle.net/shdong/wx5Lzs4v/)
把你具体的页面源码发一下，我再看下~

**Comment by zhangmengcheng** [comment]
确实，你这个没有 ，我按照你的这个实例去试试，谢谢！



715417165@qq.com
 
发件人： shdong
发送时间： 2017-09-07 10:26
收件人： mipengine/mip-extensions
抄送： zhangmengcheng; Author
主题： Re: [mipengine/mip-extensions] 表单提交为什么要限制password? (#798)
我这边没复现这个问题，如下DEMO：
mip-form password DEMO
把你具体的页面源码发一下，我再看下~

**Comment by dongshihao** [comment]
问题解决了吗？如果已经解决，将于周四之前关闭此issue。

**Comment by zhangmengcheng** [comment]
好的已经解决，谢谢告知！



715417165@qq.com
 
发件人： shdong
发送时间： 2017-09-26 10:34
收件人： mipengine/mip-extensions
抄送： zhangmengcheng; Author
主题： Re: [mipengine/mip-extensions] 表单提交为什么要限制password? (#798)
问题解决了吗？如果已经解决，将于周四之前关闭此issue。

**Comment by huanmeng122** [comment]
![2](https://user-images.githubusercontent.com/29424612/32042171-408fba04-ba69-11e7-8080-96f62ae56c9a.png)

![1](https://user-images.githubusercontent.com/29424612/32042087-08ae7526-ba69-11e7-9f1c-809bfea1af42.png)

请问，出现这样的报错是什么问题呢？
