### ISSUE TITLE
我们的自动加载与miplist组件，很多自己封装并add了部分html标签

### ISSUE THREAD

**Issue by zhangmengcheng** [mipengine/mip-extensions#799]
## 问题分类

（请在括号中输入"x"来选择）
- [ x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
我们的自动加载与miplist组件，很多自己封装并add了部分html标签

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
百度Mip很多自己封装的组件，都添加了很多HTML标签，这样对自己组件有影响，如：轮播图与mip-list这样就无法满足百度的需求，导致别人必须要用自己的开发语言来替代这些，要不就需要个人提交组件开发了，如果这样就不用官方提供了，希望官方可以添加部分参数，让开发人员自己去选择是否需要 让组件自己添加HTML标签。。。

**Comment by wupengFEX** [comment]
@zhangmengcheng 部分组件中的 html 必须的，不过组件的可扩展性这方面 MIP 会综合考虑，尽量让开发者开发过程中能够有更多操作的空间
