### ISSUE TITLE
MIP上线后显示的页面标题为网站的域名，需要MIP开放list-text或者list-title属性

### ISSUE THREAD

**Issue by zhangmengcheng** [mipengine/mip-extensions#800]
## 问题分类

（请在括号中输入"x"来选择）
- [ x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
网站改造MIP后无法改变页面显示的标题，一直显示为该网站的域名URL

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:
开放页面显示标题，这样对用户体验，自己网站的推广更加友好。

## 您的建议方案
建议MIP开发页面显示的标题

**Comment by wupengFEX** [comment]
@zhangmengcheng 正在考虑，这个地方涉及到帐号相关问题，所以可能会稍慢一些，辛苦稍稍等待！

**Comment by jennyliang220** [comment]
页面顶部标题栏不属于mip负责的范畴，而是由百度搜索控制的。页面修改为合法mip之后，需要接入百度的官方号。页面title定制是官方号提供的服务之一。官方号qq群：529767259
