### ISSUE TITLE
Mip站点使用百度加速导致验证不通过

### ISSUE THREAD

**Issue by 99shuku** [mipengine/mip-extensions#805]
mip站点使用百度加速后，百度加速会在页面中自动插入一个script标签，如下：

```
<script type="text/javascript"  src="//idm-su.baidu.com/su.js"></script>
```

**Comment by dongshihao** [comment]
MIP 规范不允许在页面内加载除 MIP 核心框架和组件之外的 JS；
MIP 页面的 JS 加载必须是异步非阻塞的，必须加`async`属性；
MIP 页面对于有特殊加载 JS 需求一般考虑封装组件满足规范。

MIP 项目组正在评估此问题，可能需要你额外的开发，也可能是 MIP 项目组提供支持。请耐心等待回复~

**Comment by dongshihao** [comment]
请把所有外链的脚本以 AMD 模块 `require` 进来，提交组件平台审核。
