### ISSUE TITLE
mip-stats-baidu 点击事件 数据异常。

### ISSUE THREAD

**Issue by hejieye** [mipengine/mip-extensions#806]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
怀疑统计组件有失效，现在页面的统计量严重下降，之前每天的点击量有11万左右，到现在每天只有几十个点击量。

统计的组件
<script src="https://mipcache.bdstatic.com/static/v1/mip-stats-baidu/mip-stats-baidu.js"></script>

统计的token
<mip-stats-baidu token="7a4095850fae5c068afbb88ce8d64c7d"></mip-stats-baidu>

加载事件
<div data-stats-baidu-obj="%7B%22type%22:%22load%22,%22data%22:%22%5B'_trackEvent',%20'M_%E9%97%AE%E9%A2%98%E8%AF%A6%E7%BB%86%E9%A1%B5',%20'%E5%8A%A0%E8%BD%BD',%20'M_%E7%B1%BB%E4%BC%BC%E9%97%AE%E9%A2%98_%E5%8A%A0%E8%BD%BD'%5D%22%7D"></div>

点击事件
<a target="_blank" href="http://m.iask.sina.com.cn/b/1mIvphZCReQl.html" data-stats-baidu-obj="%7B%22type%22:%22click%22,%22data%22:%22%5B'_trackEvent',%20'MIP',%20'MIP%E8%B7%B3%E8%BD%AC',%20'MIP%E7%B1%BB%E4%BC%BC%E9%97%AE%E9%A2%98'%5D%22%7D"> 请问有没有谁知道成都禁养区补偿金是怎...</a>

访问地址：http://m.iask.sina.com.cn/mib/4R1ixu77yV.html

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by dongshihao** [comment]
MIP 项目组未对此组件进行升级，可能不是组件的问题，详细排查下统计的使用方式和参数设置。
同时，提供更详细的信息，比如：哪些点击，点击的url和参数。我们好帮你一起追查。

**Comment by momofan** [comment]
目前统计组件对于点击事件的统计，只要初始化在页面上有的元素才能统计得上，如果是 js 加载进去的，还不支持。多个 token 的情况下，点击统计都会默认记在第一个 token 上 @hejieye 辛苦排查一下是否是使用方式有些问题

**Comment by dongshihao** [comment]
@hejieye 问题解决了吗？
