### ISSUE TITLE
mip-infinitescroll 组件在 初始化页码时目前只能静态化

### ISSUE THREAD

**Issue by zhangmengcheng** [mipengine/mip-extensions#807]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [X ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
mip-infinitescroll 组件在 初始化页码时目前只能静态化,如果我目前开发一个自动加载功能，页码也只能静态化针对用户来说，该页码无法静态；在使用中我还发现就算静态了该页码（或者说是总数），如果我该组件中的信息只有一页，而该组件就会针对静态页码的请求永远请求第一个ajax，这样对我来讲基本这个功能就是BUG了，如果可以麻烦MIP的人员增加一个请教数据并接收返回数据，这样我们就可以针对改页码自动初始化，谢谢！

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by dongshihao** [comment]
`mip-infinitescroll `初始化的时候不能知道总页码吗？新开一个接口不是必须的。
页码只有1的时候请求的问题，我们这边正在排查~

**Comment by zhangmengcheng** [comment]
初始化总页码确实不知道

**Comment by momofan** [comment]
@zhangmengcheng 辛苦配一下图吧，描述看起来有点不好理解
