### ISSUE TITLE
mip-form 支持 fetch 的 ajax 请求，实现用户输入的页面部分刷新功能

### ISSUE THREAD

**Issue by momofan** [mipengine/mip-extensions#815]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
目前 mip-form 只支持跳出的方式，无法实现当用户输入时，想部分刷新页面的功能

**Comment by xuexb** [comment]
赞~ 瞬间脑补了以下场景:

1. 注册页面的`username`重复提示
1. 某个表单标题的`sug`提示
2. 意见反馈, 提交后不跳转页面, 直接显示: 谢谢~
3. 整个表单异步提交~
