### ISSUE TITLE
firstInviewCallback在手机百度中异常

### ISSUE THREAD

**Issue by sy3tem** [mipengine/mip-extensions#817]
环境：IOS10.3.3+手机百度9.2.1
问题复现：
在手机百度添加关注 携景财富网 点开任意文章页。下拉至页面底部，触发firstInviewCallback区域会导致页面滚动到起始位置。

**Comment by jennyliang220** [comment]
能给出具体复现步骤，URL或者录屏么？我测试未发现有类似问题。但评论因为没有占位（layout），导致页面跳动一下。
