### ISSUE TITLE
mip-showmore组件的展示问题

### ISSUE THREAD

**Issue by jiangzhuorong** [mipengine/mip-extensions#819]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
1.设置可视区域的高度时，内容不足，还显示展开按钮以及按钮和内容之间的留白。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：http://ask.39.net/html5/mip/mip-ask-search-produce-4.html
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
1.设置可视区域的高度时，内容不足可视区域的高度时隐藏按钮并且可视区域高度与内容等高。

**Comment by dongshihao** [comment]
目前方案：页面取消`mip-showmore`组件的多层嵌套，改为单层。
长期方案：正在产出和解决。

**Comment by xiaojinping** [comment]
该组件在微信中使用时，点击展开更多，对于我们开发人员来说，知道他是执行了什么操作，但是对于用户来说，给用户的体验是找不到位置，我不知道我现在处在哪个位置，还以为是重新刷新了，我也是往上滚动了下，才知道是怎么回事。这对用户而言，很不友好，

**Comment by zhuguoxi** [comment]
https://github.com/mipengine/mip-extensions/pull/1166
