### ISSUE TITLE
mip-stats-baidu统计流量异常

### ISSUE THREAD

**Issue by yaomeizi** [mipengine/mip-extensions#832]
平台使用mip-stats-baidu插件统计流量，10万的流量只能统计到几十个。

<div class="none">
 <mip-stats-baidu token="56ce04ea7a942ebbecb19ee9a13ea6a9"></mip-stats-baidu>
 </div>

站点url：https://mip.66law.cn/laws/9677.aspx

**Comment by momofan** [comment]
已解决关闭
