### ISSUE TITLE
mip-carousel组件滚动图片高度

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#835]
mip-carousel组件滚动图片高度

    width="300" 
    height="600"

请问宽与高，如何自动适应手机屏幕？不能使用100%及auto自动适应

**Comment by lrvingyang** [comment]
上传图片的宽高都不是固定的，所以需要能自动适应，要不然图片会变形

**Comment by wupengFEX** [comment]
@lrvingyang 请参考组件[布局方式](https://www.mipengine.org/doc/3-widget/11-widget-layout.html)

**Comment by lrvingyang** [comment]
@wupengFEX 只能控制容器大小，容器内图片会变形。

<mip-carousel
    autoplay
    defer="4000"  
    layout="responsive" 
    height="290"
    width="300" 
    buttonController>
        <mip-img 
        src="http://kmgmy.com/<%=rs("img1")%>">
        </mip-img>
