### ISSUE TITLE
mip-carousel 多图轮播

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#836]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [x ] MIP 页面内容（广告不显示，排版错乱）
- [x ] MIP-Cache下效果异常

## 问题描述
m.kmgmy.com/photo.asp   

图片变形、有图片不会显示

## 复现方式（线上bug 填写此项）
1. 手机型号：iphone
2. 系统版本：11\10
3. 浏览器及版本：
4. 页面URL：m.kmgmy.com/photo.asp  
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： m.kmgmy.com/photo.asp  
2. 效果描述:

## 您的建议方案

希望可以自动适应屏幕大小，图片不变形，图片能够完整显示。

**Comment by wupengFEX** [comment]
@lrvingyang 轮播图里的图片是如何写入的？看dom结构应该js插入的，里面有100张图片轮播，并且一部分没有渲染，图片插入细节麻烦附上具体代码或文件地址

**Comment by lrvingyang** [comment]
图片是程序读取输出打印，不是JS调用，图片大小格式不一样，组件不能适应大小，很多图变形了！

代码如下
  | <mip-carousel
  | autoplay
  | layout="responsive"
  | defer="4000"
  | height="100"
  | width="100"
  | indicator
  | buttonController
  | >
  |  
  | <mip-img
  | src="http://kmgmy.com/file/201743017191127546.jpg">
  | </mip-img>
  | </mip-carousel>

**Comment by lrvingyang** [comment]
<mip-carousel
   autoplay
    layout="fixed-height" 
    defer="4000"  
    height="300"
    indicator
    buttonController 
       > 
<%set rs=server.CreateObject("adodb.recordset")
Randomize
sql="select  * from run_img order by Rnd("&Rnd()&"-id)"
rs.open sql,conn,1,1
       Do While not Rs.EOF%>
       <%if rs("img1")<>"" then%>
        <mip-img 
        src="http://kmgmy.com/<%=rs("img1")%>">
        </mip-img>
        <%end if%>
	 <% Rs.MoveNext
	  Loop
	  Rs.Close
	  Set Rs=nothing%>
</mip-carousel>

**Comment by wupengFEX** [comment]
@lrvingyang 排查了下是你的页面问题，页面里包含了3个mip.js的引用，这是不正确的做法，导致了页面部分图片不显示。

另外对于图片如何显示，请通过[layout布局](https://www.mipengine.org/doc/3-widget/11-widget-layout.html)来操作，如希望根据子节点大小撑开，请选择container布局

**Comment by lrvingyang** [comment]
layout布局来，节点大小，请问有demo代码吗？

**Comment by wupengFEX** [comment]
提供两种思路，具体需要按照站点需求来决定。
1. 如果所有图片有共同比例，建议通过responsive，并指定width和height限定比例；
2. 如果有特殊需求，如所有图片尺寸无规律可循，同时很难将所有图片尺寸归一化，也可以自定义css来覆盖样式，如
```
.className mip-img img {
    max-width: 100%;
    height: auto !important;
}
```
但这种情况下需要注意整体样式是否正常。

**Comment by lrvingyang** [comment]
好的，感谢！
