### ISSUE TITLE
mip-bind双向数据绑定组件

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip-extensions#839]
# MIP Bind 设计文档

通过该功能让用户可以在页面使用数据双向绑定的功能。

## 思路

- 如何绑定数据，做到一整套发布者-订阅者功能；
- 如何修改数据；

### 设置数据

```
<mip-data id="state1">
	<script type="application/json">
	{
		"data": {
			"name": "Jack",
			"name": 23
		},
		"common": {
			"baiduId": "92031238234"
		}
	}
	<script>
</mip-data>

<mip-data id="state2" src="https://www.mipengine.org/common">
</mip-data>
```

其中 mip-data 用于在页面中设置数据源，有两种形式：

- 如果不经过请求，可通过 json 形式写入 script 脚本中；
- 如果需要请求，则指定 src 地址，在请求回来之后，mip-data 更新页面总 datasource （所有 mip-data 中的数据会组合成一张 dataSource 表，其实也就是一个对象，merge时如果有相同字段，则后面的覆盖前面的），同时更新页面展现的数据（数据双向的作用）；
- 一个页面可以写多个 mip-data；

### 模版语法
- 指令

	所有指令后的值都会通过 jison 进行解析，所以可以是普通值，也可以是表达式；
	
	- m-bind：绑定元素属性；

		```
		<div m-bind:id="dynamicId"></div>
		```

		其中绑定 class 有两种方式，支持对象和属性两种类型；

		```
		<div m-bind:class="{ active: isActive, 'text-danger': hasError}"></div>
		<div m-bind:class="[activeClass, errorClass]">
		```	

	- m-text：以文本形式展示；

		暂时不需要该指令，直接通过 mustache 语法来渲染；	

- 如何动态设置：通过属性中书写 MIP.setState({}) 即可，该方法可以在组件中调用，也可以在页面 html 中书写；

	```
	<button on="tap:MIP.setState({foo: 'mip-bind'})">
	```

## 修改数据

- 通过 MIP.setState({}) 设置数据；
- 通过事件来修改：在 html 页面里，将 MIP.setState({}) 绑定在事件上，事件列表如下：

	- 全部元素

		事件|描述
		----|----
		tap|单机的情况下触发
		doubleTap|双机的情况下触发

	- input 元素

		事件|描述
		----|----
		change|包括 input type 为 range，radio，checkbox，text 的元素

	- mip-carousel

		事件|描述
		----|----
		slideChange|手动触发滑动时，自动触发不执行

	- mip-form

		事件|描述
		----|----
		submit|提交后触发
		submit-success|提交成功触发
		submit-error|提交错误后触发

- 组件中修改

	- 通过拿到 `m.` 这种方式来获取和改变数据；

### 实现方案

MIP Bind 通过数据截获来实现，实现基于 `发布者-订阅者` 模式。

![cd87a6abe0a1f4561a883a71a2deb8bef163e2f2](https://user-images.githubusercontent.com/8186657/31487100-36932312-aeff-11e7-9d50-d449d034338d.png)

- 发布者模块（Observer）

	发布者模块主要是给所有数据对象绑定一个 Observer，在数据变更的时候抛出通知给调度中心，让其通知 Watcher 订阅者进行更新视图操作。

	这一部分主要的设计思路是通过 `Object.defineProperty` 对每个数据对象进行重新定义，重写其 get 和 set 方法，在其中绑定调度中心逻辑，get 时将 watcher 加入到调度中心，set 的时候触发 watcher 的 callback（主要是处理指令的函数）。

	```
	Object.defineProperty(data, key, {
		enumerable: true, // 可枚举
	    configurable: false, // 不能再define
	    get: function() {
		    // 将该加入到调度中心
			return val;
		},
		set: function(newVal) {
			// 新的值是object的话，进行监听
			childObj = observe(newVal);
			// 通知订阅者
			dep.notify();
		}
	});
	```

- 编译模块（Compile）

	编译模块是将页面中需要处理的 dom 元素拿到 js 运行环境中进行处理，通过 fragment 插入到页面里，然后进行遍历，在编译 dom 的同时遍历它的属性。然后将其与 Watcher 进行绑定，watcher 在构造函数中会触发数据的 get 方法，目的就是将 watcher 加入到调度中心里。

- 订阅者模块（Watcher）

	订阅者模块执行时，会触发对应数据的 get 方法，此时其实 Observer 中的 get 也就触发了，然后执行回调进行视图更新；

- 调度中心

	主要充当消息分发到作用，Observer 通知了变更，则调度中心调用 Watcher 的方法。

## 兼容性

- 不处理 mustache 下的内容；

**Comment by pearlwang1106** [comment]
Object.defineProperty  可以换成  proxy 了
