### ISSUE TITLE
mip-img 文章显示效果

### ISSUE THREAD

**Issue by lrvingyang** [mipengine/mip-extensions#843]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ x] MIP 页面内容（广告不显示，排版错乱）

## 问题描述
请问，mip-img 如何实现文字围绕图片？

比如左边是图片，右边文字，文字围绕图片。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案

问题能够围绕图片显示。

**Comment by wupengFEX** [comment]
@lrvingyang 暂时还没有计划实现该功能，你可以在 css 中借助 float 之类的样式来实现排版，也可以将其封装成自定义组件。
