### ISSUE TITLE
建议官方开发百度地图组件！！！！

### ISSUE THREAD

**Issue by Edims** [mipengine/mip-extensions#853]
百度地图，作为百度系产品，目前还没发现能在 MIP 上用的组件，为什么不去做一个呢，需求很多的呀

<mip-map token="appid" mapid="mapObj" lngX="118.812583" lngY="34.104379" Zoom="14" MapIcon="IMGURL"></mip-map>

我们是用在企业黄页的企业坐标标注上了
![qq20171025-155944 2x](https://user-images.githubusercontent.com/25048319/31987178-99b4f1a6-b930-11e7-953e-f340f7f597e7.jpg)

**Comment by wupengFEX** [comment]
@Edims 目前需要的具体功能点（如定位）是什么？另外麻烦提供一个你们使用该功能的页面地址，我们可以确认和调研一下。

**Comment by Edims** [comment]
我们常用在商家的坐标位置标注啊，用户登记商家，选择他的商户所在位置，然后进行标注位置，然后展现出来。我先随便找个例子给你们看吧http://www.05273.com/house/view_33.html  类似我这种楼盘位置，wap 端显示 OK，但 MIP 就没组件支持了

**Comment by wupengFEX** [comment]
组件已上线，具体可参考[mip-map](https://www.mipengine.org/examples/mip-extensions/mip-map.html)组件文档

**Comment by Edims** [comment]
不对啊，咋没有以经纬度坐标进行定位的呢

**Comment by wupengFEX** [comment]
考虑到经纬度对开发者来说比较麻烦，所以提供的是通过详细位置或关键词搜索的功能。如果有需要经纬度的点，可以提个issue说下具体场景。

**Comment by Edims** [comment]
我们用的场景，比如http://www.05273.com/house/view_33.html

采用是正常的地图标注方法，选择地图位置，标注，并不是按照地理位置进行搜索的，记录的是经纬度 X 和 Y：

var mapObj=null;
--
  | lngX = "118.811999";
  | latY = "34.104985";

**Comment by Zeno-Code** [comment]
@wupengFEX 如果不采用经纬度 init，每次都要进行地址的二次解析，总是先展现北京，然后在解析地址，很不友好
