### ISSUE TITLE
我来提个关于自带的组件 pix 的问题

### ISSUE THREAD

**Issue by Edims** [mipengine/mip-extensions#855]
## 问题分类
MIP 组件使用
## 问题描述

我自己在开发自己特定的统计接口，但一直审核不通过，推荐来用 pix，但pix 的需求又无法满足我，所以我来提了：
pix 的最终请求参数，可否不要默认带上，我并不需要这个默认的参数，我使用中如果不带这几个参数，会在请求里自动带上，会带上TIME，TITLE，HOST三个参数，重要的是我不要这几个参数！！我不要不要不要，重要的事说三遍

## 复现方式（线上bug 填写此项）
页面URL：http://wap.05273.com/mip-10-281897-1.html
复现操作：审查元素看 network 里的op=count和op=stats 请求

## 您的建议方案

去掉默认带上的三个参数，谁爱用，谁加上，如果不能解决这个，请把我组件通过审核，组件名：mip-shuyang-count

**Comment by wupengFEX** [comment]
@Edims 审核同学已审核！
