### ISSUE TITLE
mip-from 填写password 类型，出现报错

### ISSUE THREAD

**Issue by huanmeng122** [mipengine/mip-extensions#859]
![2](https://user-images.githubusercontent.com/29424612/32042330-be934344-ba69-11e7-88e7-623d24e27278.png)
![1](https://user-images.githubusercontent.com/29424612/32042338-c38af946-ba69-11e7-90cc-985cae774dbe.png)

请问，出现这样子的报错，是什么引起的呢？

**Comment by wupengFEX** [comment]
@huanmeng122 这个是目前mip-form组件里的一个校验规则，具体我们看下是否还需要保留，状态会在这里及时更新

**Comment by nszxyu** [comment]
input只能出现在mip-form里面，然而mip-form不支持password，那么我需要完成登录注册功能该怎么办

**Comment by wupengFEX** [comment]
@nszxyu @huanmeng122 这个限制会在 #872 中去掉，另外登陆解决方案可以使用官方提供的 [ACCESS](http://www.cnblogs.com/mipengine/p/mip-access.html) 机制来解决，欢迎使用和建议！

**Comment by huanmeng122** [comment]
谢谢及时答复与解决，我要研究一下啊~

**Comment by nszxyu** [comment]
@wupengFEX mip-access的demo我打不开
