### ISSUE TITLE
mip生成的标签的css复写问题

### ISSUE THREAD

**Issue by Godyakho** [mipengine/mip-extensions#863]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

百度搜索后的结果页，有mip自动生成的标签，复写其css无效，无法修改其样式

**Comment by wupengFEX** [comment]
@Godyakho 怎么写的呢，权重是否足够？可以截图或附上源码具体分析下

**Comment by Godyakho** [comment]
![1509417096 1](https://user-images.githubusercontent.com/24286139/32204831-a4fa2220-be26-11e7-8a43-90901b3f7d42.png)
![903e1eef-cbca-409c-b0b2-c6d239357729](https://user-images.githubusercontent.com/24286139/32204832-a7956486-be26-11e7-85f5-94f49b1198d0.png)
上面的是生成的
![c41d2669-4413-4cd8-b562-2b52464f1d7d](https://user-images.githubusercontent.com/24286139/32204844-b94cb1fc-be26-11e7-82a7-8be395be2ae5.png)
这个是我写在<style mip-custom></style>

**Comment by wupengFEX** [comment]
@Godyakho `b-scene-header` 不是 mip 标签，你这段样式是通过什么方式加进去的？麻烦提供个页面URL

**Comment by Godyakho** [comment]
@wupengFEX  这个链接 https://m.baidu.com/mip/c/m.chinabyte.com/
想隐藏 b-scene-header 里的内容 ，这个头部是自己生成的

**Comment by wupengFEX** [comment]
- 先说为什么设置改不了样式？mip页面是在iframe里嵌套着，`b-scene-header`是在iframe外，所以你在mip页设置的样式不会影响iframe外的样式；
- 其次为什么有这样的策略？目前对于搜索引擎点出的mip页面都会带上这样一个栏目，这也是类似`native`的一种体验效果，是不能通过代码来修改的。

**Comment by Godyakho** [comment]
@wupengFEX  好的，谢谢了。因为头部占用地方有点多，而且logo重复了，所以想要隐藏，那我写个组件通过找那个标签改样式可以吗，之前写过没通过，说单纯改样式不让提组件

**Comment by wupengFEX** [comment]
看下我的上一条回复，这个是从搜索引擎点出的mip页的统一样式，目前是不允许修改和隐藏的
