### ISSUE TITLE
mip-sidebar 兼容问题反馈

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#887]
## 问题分类

- MIP 组件使用

## 问题描述

打开 mip-sidebar 组件时先由全部展开状态->全部关闭状态->动画展开状态的过程，呈现出就是闪烁感。

## 复现方式
1. 手机型号： iphone X
2. 系统版本：ios 11.1
3. 浏览器及版本：safari、QQ浏览器、手机百度、UC浏览器
4. 页面URL： <https://xuexb.github.io/learn-mip/src/mip-sidebar/>
5. 复现操作：点击打开按钮即可

**Comment by wupengFEX** [comment]
@xuexb 暂时不能复现，顺带优化了sidebar弹出层动画效果，已上线。
