### ISSUE TITLE
mip-infinitescroll 组件无限下拉参数优化

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#893]
## 问题分类

- MIP 组件使用

## 问题描述

使用 mip-infinitescroll 组件时，如果站点的时效性很高，在配置属性字段 `rn` （这个字段名也是醉了）为固定的数值时，页面被缓存后，可能真实的数据和配置的字段数值有偏差，导致页面加载可能有问题。

并且有些网站数据量可能很大，查询总数可能不太方便。

## 您的建议方案

可以增加 `rn: null` 配置，让前端代码根据后端返回的数据去判断是否有下一页。如返回 `items: []` 时认为没有数据：

```js
{
    status: 0,
    data: {
        items: [] 
    }
}
```

注意的事，需要在文档中说明，如果参数配置成 `rn: null` 则依赖后端返回数据判断是否有下一页，因为有些后端在 `page` 参数大于数据时会返回最后一页数据。

**Comment by jennyliang220** [comment]
看了下mip-infinitescroll的代码和使用，发现两个修改点。
### 1. 让前端代码根据后端返回的数据去判断是否有下一页
先说结论：不需要改代码，改下文档就好了。  @xuexb知晓   
看了[代码](https://github.com/mipengine/mip-extensions/blob/d70a02e5a8022b68e57edef25bd3725b7e466ad3/src/mip-infinitescroll/mip-infinitescroll.js#L81)，有个逻辑是“当后端数据的index大于限定值rn，则不插入页面” 。
![041498ae6e4676649c579dff2b5d5867](https://user-images.githubusercontent.com/8498677/33976975-69c06df2-e0d3-11e7-9691-93f4edfe588e.png)

而通过AMD引入的 infintite.js本身是支持根据后端数据判断数据加载完毕的。
![image](https://user-images.githubusercontent.com/8498677/33977086-0fccc81c-e0d4-11e7-97be-be2f31b8e0be.png)

所以，如果rn填的是[Infinity](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Infinity)就可以实现无限加载数据。我来改下文档~

### 2. 组件可用配置文档缺失
组件代码中支持prn的配置(这个命名也是颇为简略），代表 pageResultNum，每页加载条数，文档中没有说明。我加上吧。
![image](https://user-images.githubusercontent.com/8498677/33977154-8796e0da-e0d4-11e7-83da-0c7b313503b3.png)

**Comment by xuexb** [comment]
@jennyliang220  如果已经支持根据后端数据来判断是否有下一页的功能，请优化下文档，让其可以明确知道后端需要返回什么值或者状态码来配合~
