### ISSUE TITLE
百度统计中，如何看MIP站的受访页面？

### ISSUE THREAD

**Issue by yvoooneguo** [mipengine/mip-extensions#908]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
地址1：https://m.baidu.com/mip/c/s/m.51credit.com/mip/wenda/115810.html
地址2:  https://m.baidu.com/mip?ext=%7B%22lid%22%3A%229713461157839940609%22%2C%22url%22%3A%22%2F%2Fmipcache.bdstatic.com%2Fc%2Fs%2Fm.51credit.com%2Fmip%2Fwenda%2F115810.html%22%7D&title=%E4%BF%A1%E7%94%A8%E5%8D%A1%E5%8F%AF%E4%BB%A5%E5%8F%96%E7%8E%B0%E9%87%91%E5%90%97
地址1和地址2百度统计受访页面搜索不到，而实际上页面来源为mipcdn.com和mipcache.bdstatic两个域名，不在m.baidu.com域名之下

## 您的建议方案
添加对百度统计中受访页面的详细解释，减少站点对于统计的误解

**Comment by jennyliang220** [comment]
![f71d1f56aed8778e91a19033b4aacfbd](https://user-images.githubusercontent.com/8498677/32939617-12b4634c-cbbb-11e7-90ae-32c83877877a.png)


不添加筛选项，可以看到所有统计数据。MIP-Cache流量URL有`mipcdn.com`或`mipcache.bdstatic.com`的特点，筛选可见。不能筛选`m.baidu.com`
