### ISSUE TITLE
mip-audio使用文档更新

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip-extensions#911]
目前mip-audio没有对应的使用文档，需进一步进行优化补充

**Comment by jennyliang220** [comment]
一句话概括mip-audio的代码逻辑：将src配置项传入新建的`<audio>`标签里，并自己实现了controls。使用文档可写的也只有以下示例，没有更多配置项可选。
```
<mip-audio 
    src="https://www.mipengine.org/static/RonaldJenkees-GuitarSound.mp3"
></mip-audio>
```

**Comment by Chang1ng** [comment]
可以把音频的时间展示讲解更清晰一点~有些场景下是需要分别展示播放时间和音频的总时长。

**Comment by jennyliang220** [comment]
https://github.com/mipengine/mip-extensions/issues/926

**Comment by jennyliang220** [comment]
已上线：https://www.mipengine.org/examples/mip-extensions/mip-audio.html
自定义控件皮肤
使用 controller 属性在<mip-audio>中声明自定义交互控件。可以任意更改DOM位置，通过增加class及css为控件添加皮肤。
