### ISSUE TITLE
mip-stats-cnzz节点问题优化

### ISSUE THREAD

**Issue by wupengFEX** [mipengine/mip-extensions#912]
问题
- 目前的cnzz统计组件节点单一，不能支持站点自定义节点；
- s11节点总出现问题，需求默认有稳定节点来控制；

方案
- 加入站长定制的节点参数；
- 挑选一些稳定节点作为默认参数。

**Comment by schoeu** [comment]
👍

**Comment by xiaojinping** [comment]
大概什么时候可以完成这项工作

**Comment by wupengFEX** [comment]
@xiaojinping 已经在测试中，预计下周一左右可以上线

**Comment by wupengFEX** [comment]
@xiaojinping 组件功能已上线，具体可参考[mip-stats-cnzz](https://github.com/mipengine/mip-extensions/blob/master/src/mip-stats-cnzz/README.md)组件文档。
