### ISSUE TITLE
建议mip-ad的支持百度图+功能

### ISSUE THREAD

**Issue by caowhgzs** [mipengine/mip-extensions#913]
## 问题分类
- [x ] MIP 组件使用
- [x ] MIP 页面内容（广告不显示，排版错乱）

## 问题描述
MIP官网上mip-ad的组件，写明支持百度图+功能。但引入代码后（通过MIP校验），尝试多个终端都无法显示百度图+的广告。经咨询mip-support@baidu.com，是因为目前图加广告暂时不能使用。

## 需求描述
我的站图片内容较多，因此建议按照官网的说明代码支持mip的百度图+功能：
<mip-ad 
    type="ad-imageplus"
    unionId="u888888"
    >
</mip-ad>
## 您的建议方案
建议开发

**Comment by momofan** [comment]
图加服务由于 https 证书问题，组件下线了，重启开发计划
