### ISSUE TITLE
开发辅助工具和模块

### ISSUE THREAD

**Issue by xiaojinping** [mipengine/mip-extensions#924]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [ ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
开发辅助工具和模块 看了这个章节的内容 ，始终没有明白，这个辅助工具怎么开发。文档中有提到event-action，允许开发人员自定义一个函数，然后在页面中通过on="tab: 自定义函数名 “的方式 来调用 。不明白的是，我这个自定义函数，定义在什么地方， 是通过组件形式提交吗？如果是这样，我是不也必须通过组件来调用。还是说单独提交一个js文件 。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by wupengFEX** [comment]
@xiaojinping 
- 你提到的是 mip-bind 的功能吗？
- 如果是，需要做的操作是否是设置数据？

**Comment by xiaojinping** [comment]
收到，谢谢。

**Comment by xiaojinping** [comment]
官网安例当中有个这样的。
define(function (require) {
    var customEle = require('customElement').create();
    customEle.prototype.build = function () {
        // 绑定事件，其它元素可通过 on="xxx" 触发
        this.addEventAction("custom_event", function (event/* 对应的事件对象 */, str /* 事件参数 */) {
            console.log(str); // undefined or 'test_button' or 'test_button1'
        });
    };
    return customEle;
});

event/* 对应的事件对象 */ 这个event是指什么 。我需要怎么传递这个参数。
