### ISSUE TITLE
mip-bind 按需异步请求数据

### ISSUE THREAD

**Issue by JasonDurian** [mipengine/mip-extensions#932]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
现在使用mip-bind设置数据后，需要将此数据（可能是某个object中的键值对）作为fetch的body参数来发起异步请求，然后请求到的值存入mip-data中
类似这样发起请求
![ee y j28ggos14_0oy 9sj](https://user-images.githubusercontent.com/24243477/33255976-e8aaa2e6-d38a-11e7-9a78-84ac0539e46b.png)

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
我建议可以使用一个新组件来结合mip-bind实现，那个组件的功能类似于mip-form，但是请求内容获取的是mip-data中的数据

**Comment by JasonDurian** [comment]
还有在MIP.setData操作后的其他事件，似乎都不起作用，例如on="tap:MIP.setData({params:{username:m.others,sex:'female'}}) tap:mip-fj-fetch-id.event_fetch"中MIP.setData之后的操作；
另外，像上面多级的object数据，例如想单独设置params.username该如何设置MIP.setData({params.username:m.others})会报错

**Comment by wupengFEX** [comment]
@JasonDurian mip bind设置数据分为两种：
- 固定数据
不经过异步请求，可通过 application/json 形式写入，里面的内容是我们需要使用的数据，如：
```
<mip-data>
    <script type="application/json">
    {
        "name": "张三",
        "age": 25,
        "job": {
            "desc": "互联网从业者",
            "location": "北京"
        }
    }
    </script>
</mip-data>
```
- 异步请求数据
只需指定 src 地址即可，如：
```
<mip-data src="https://www.example.org/data"></mip-data>
```

可能你理解的有点误区，其实你所说的问题就是目前的实现方式，我们通过 mip-data 组件处理所有 mip-bind 的数据，包括固定和异步数据：
- 第一：通过固定数据的方式书写的数据不需要发起任何请求，直接拿其中的 json 数据作为页面
 datasource（数据源）的一部分；通过异步数据获取，只需要配置请求地址即可，数据返回后 merge 进datasource。
- 第二：异步请求获取的数据不会塞进 mip-data 里，而是维护在以 `m.` 打头的一份 datasource 里。

**Comment by JasonDurian** [comment]
@wupengFEX 感谢回复。但是我现在的需求不是页面加载时获取mip-data数据，而是通过其他操作来异步请求

**Comment by wupengFEX** [comment]
@JasonDurian 

1. 设置数据不起作用
```
on="tap:MIP.setData({params:{username:m.others,sex:'female'}}) tap:mip-fj-fetch-id.event_fetch"
```
设置数据必须通过 `on="事件名:MIP.setData({})"` 的形式，测试数据有没有生效，最简单的方法就是打开控制台，输入 m.，然后根据层级找找自己的数据有没有在里面，如：
```
on="tap:MIP.setData({info:{name: 'Jack'}})"

// 控制台获取
m.info.name
```

2. 多层级数据目前只能通过对象层级来设置，如：
```
MIP.setData({params:{userName: 'Jack'}})
```
不支持将 key 直接设置为 params.username

3. 如果期望通过其他操作来设置数据的话，比如组件内通过js请求，然后把数据赋值给 mip-bind 数据源，可以通过全局方法 MIP.setData 或 MIP.$set 来设置，方法后者会 observer 数据，但是也会编译页面中的
 dom，有性能开销，另外组件内也支持通过 m. 来获取数据。

**Comment by xuexb** [comment]
@JasonDurian 的意思是不是想在组件中使用全局的数据去请求接口，并把合适的返回值设置到全局数据中？

那看样子是需要自定义组件了，在代码里手动的获取数据请求，并在成功（也可经过处理）的数据再设置到全局中了。

@wupengFEX 设置数据的方法可以使用统一的  `MIP.setData` 吗？而不是 `MIP.$set` 。

**Comment by JasonDurian** [comment]
@wupengFEX 
多谢热情的回复，让我对遇到的问题有了更深入的理解。
不过还有一点就是
on="tap:MIP.setData({params:{username:m.others,sex:'female'}}) tap:mip-fj-fetch-id.event_fetch"
不是设置数据不起作用，而是后一个tap事件不起作用。
包括1、on="tap:MIP.setData({params:{username:m.others}}) tap:MIP.setData({params:{sex:'female'}})"
2、on="tap:MIP.setData({params:{username:m.others}}) change:MIP.setData({params:{sex:'female'}})"
后一个事件都不起作用

**Comment by JasonDurian** [comment]
@xuexb 是的

**Comment by wupengFEX** [comment]
@JasonDurian 第二个表达式不执行确实是，这个我们最近修复一下。

@xuexb 两个方法使用场景不太相同，`setData` 是对现有数据源中的数据修改，不会重新编译 dom 和设置观察关联，一般适用于已在 datasource 里存在的数据，$set 会编译 dom，一般用于当前观察的数据中未存在的数据（不过需要谨慎使用，性能考虑的话）。

**Comment by Wanghengfeng** [comment]
最开始提的那个按需异步获取mip-data数据的问题，有办法实现吗？只能自己写组件实现？
