### ISSUE TITLE
mip-form 中fetch请求处理成功状态的逻辑

### ISSUE THREAD

**Issue by JasonDurian** [mipengine/mip-extensions#936]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
对于大多数的fetch/ajax操作来说，只有返回了特定的status时，才算作submit success，不过现在在使用mip-form的fetch时发现，只要fetch返回状态ok时就算做submit success了。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
从
![38wgdtuue5gxyqqc 967vgg](https://user-images.githubusercontent.com/24243477/33300384-f52b1a6e-d42a-11e7-8931-36fd504c09f4.png)

改为
![122 h3y_k j7 osl1fjm f](https://user-images.githubusercontent.com/24243477/33300355-c83706f8-d42a-11e7-96be-6a0cc6e089da.png)

**Comment by wupengFEX** [comment]
@JasonDurian 这是一个比较好的建议，通过开发者数据状态决定最终状态，我们看看请求这块如何来优化下，但涉及向后兼容（一些站长接口中没有status类似的字段），同时也需要有一个标准来规范，所以优化周期会稍微长一点。

**Comment by JasonDurian** [comment]
好的，我现在所做的项目很多操作都涉及了这一块，希望尽快优化。

**Comment by xuexb** [comment]
#1074
