### ISSUE TITLE
event-action 无法捕捉<select>的change

### ISSUE THREAD

**Issue by JasonDurian** [mipengine/mip-extensions#942]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
为<select>添加on="change:xxx.xxx"操作时，没有办法触发事件；但是在on="tap:xxx.xxx"时可以触发一次。

为<select>添加on="change:xxx.xxx"操作时，没有办法触发事件；但是在on="tap:xxx.xxx"时可以触发一次。

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：http://jsbin.com/nomusey/2/edit?html,output

## 您的建议方案
可能是因为select点击option时，event的target是option吧。

**Comment by wupengFEX** [comment]
@JasonDurian 现在只有 input 元素支持 change 事件 ，如果[官方提供](https://www.mipengine.org/examples/mip-extensions/mip-bind.html#markdown-doc-%E4%BA%8B%E4%BB%B6%E7%B1%BB%E5%9E%8B)的不能满足需求，可以[自定义事件](https://www.mipengine.org/examples/mip-extensions/mip-bind.html#markdown-doc-%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6)的。

**Comment by JasonDurian** [comment]
好的
