### ISSUE TITLE
在某些情况下firstinviewcallback无法触发，

### ISSUE THREAD

**Issue by gom3250** [mipengine/mip-extensions#953]
按道理是可以触发的，但是实际上线无法触发，改成build就可以了。
该功能已经下线，使用的组件是 https://mipcache.bdstatic.com/extensions/platform/v1/mip-qqtn-addmore/mip-qqtn-addmore.js
这个组件是用来给一个选项卡进行下拉加载的。不同的选项卡加载不同的数据。
当时跟一个审核小哥讨论过，他也不是很清楚原因是什么。。。

**Comment by wupengFEX** [comment]
@gom3250 辛苦给一个能复现的 URL。有一些人为操作也可能导致这个问题：比如可能是 css 样式设定，导致元素在屏幕之外了，自然 firstinviewcallback 也无法触发了。
