### ISSUE TITLE
异步请求不换号

### ISSUE THREAD

**Issue by wapjia** [mipengine/mip-extensions#956]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
使用mip-list异步请求数据的时候设计到了文字汉化问题
直接使用\n发现只显示一个空格不能正常换行，替换成<br(防)/>是直接显示<br(防)/>而不是换行

*(防)为了显示正常，请直接忽略

**Comment by wupengFEX** [comment]
@wapjia 返回的数据都会当作文本进行处理的，所以会出现你说的问题，不过文本的换行之类也可以通过 css 来控制，比如 `white-space: pre-wrap`，不过需要测试好兼容性。
