### ISSUE TITLE
mip-stats-baidu 使用优化反馈

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#961]
## 问题分类

-  MIP 组件使用

## 问题描述

在 [mip-stats-baidu组件文档](https://www.mipengine.org/examples/mip-extensions/mip-stats-baidu.html#markdown-doc-%E4%BA%8B%E4%BB%B6%E8%BF%BD%E8%B8%AA) 中，强调说明了必须使用 `encodeURIComponent` 进行转义，但为啥转义的目标值不是“正常”的 JSON 结构呢？如：

```html
<div data-stats-baidu-obj="%7B%22type%22:%22click%22,%22data%22:%22%5B_trackPageview,%20/virtual/login%5D%22%7D">
    我是自动触发
</div>
```

中的 `data-stats-baidu-obj` 转义前是：

```JSON
{
    "type": "click",
    "data": "[_trackPageview, /virtual/login]"
}
```
这个 `data` 是个字符串？

因为我要使用 [百度统计事件API](http://tongji.baidu.com/open/api/more?p=ref_trackEvent) 来完成自定义需求，但发现这个 `data` 不是 `"data":["_trackPageview", "/virtual/login"]` 这样的，这在使用后端往页面输出 `JSON.stringify(obj)` 时很尴尬。

## 您的建议方案

```JSON
{
    "type": "click",
    "data": [
        "_trackEvent",
        "tpl",
        "down",
        "1"
    ]
}
```

**Comment by xuexb** [comment]
<http://tongji.baidu.com/open/api/more?p=ref_trackEvent> 百度统计API里是个数组形式，而到组件就是个字符串了。

**Comment by jennyliang220** [comment]
确实很奇怪，使用字符串比较别扭。看了代码blame，chuantao之前增加事件追踪的时候是这么设计的：
![image](https://user-images.githubusercontent.com/8498677/34510819-2f85e6d4-f092-11e7-93f7-0586ed5ace14.png)，如果没有特殊原因，我改下代码，兼容数组和字符串吧。

**Comment by fengchuantao** [comment]
当时的设计没有特殊原因，可修改后兼容数组。 @jennyliang220

**Comment by jennyliang220** [comment]
#999 修复这个问题，2018.1.18已上线。上线后支持以下三种统计方法：

```html
<!--语义化最好，推荐-->
<button data-stats-baidu-obj='{"type":"click","data":["_trackPageview", "/virtual/login2"]}'>
    点击直接触发统计 virtual/login2
</button>

<button data-stats-baidu-obj='{"type":"click","data":"[_trackPageview, /virtual/login3]"}'>
    点击直接触发统计 virtual/login3
</button>

<button data-stats-baidu-obj="%7B%22type%22%3A%22click%22%2C%22data%22%3A%22%5B_trackPageview%2C%20%2Fmip-stats%2Fsheji%5D%22%7D">
     点击触发统计 mip-stats%2Fsheji
</button>
```

**Comment by xuexb** [comment]
666
