### ISSUE TITLE
mip-form验证规则在checkbox校验时存在问题

### ISSUE THREAD

**Issue by nordon-wang** [mipengine/mip-extensions#965]
- 提问题之前，请在 issue 历史中搜索是否有同类问题。
- 第三方组件问题，可直接提交pull request
- 百度收录问题，请在[站长平台-反馈中心](http://zhanzhang.baidu.com/feedback/index?type=1180&name=MIP%E5%BC%95%E5%85%A5)反馈。

## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
checkbox必填，checkbox的name是保持一致的，校验可以使用，但是存在一个问题，即多个相同name的checkbox在校验时，既然不是没有做处理，每一个checkbox都单独进行校验，而不是一组checkbox进行校验

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

## 您的建议方案
对checkbox校验进行处理，一组checkbox进行校验试，有一个勾选，则这组checkbox则通过校验

**Comment by wupengFEX** [comment]
@nordon-wang 感谢反馈，因为每一个 checkbox 都可以绑定对应的校验规则，如果一组中只校验一个的话那不是不能覆盖全部了吗？
