### ISSUE TITLE
mip-infinitescroll 参数优化

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip-extensions#974]
## 问题分类

-  MIP 组件使用

## 问题描述

[mip-infinitescroll](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html) 组件中的 `data-src` 参数并没有说明是 `JSONP` 或者使用 `CORS` 解决跨域，然而看**异步接口示例**我想使用 `CORS` 但发现不行。

## 您的建议方案

如果只支持 `JSONP` 的话请在文档中说明。

**Comment by xuexb** [comment]
还有 [mip-list](https://www.mipengine.org/examples/mip-extensions/mip-list.html) 的参数居然是 `src` 。。。并且她的参数是用**属性化**，而不是 `JSON` 配置化。

能不能统一？

**Comment by xuexb** [comment]
还有 `class="mip-infinitescroll-results"` 、 `class="mip-infinitescroll-loading"` 是什么鬼？

<https://github.com/mipengine/mip-extensions/blob/7153faf68906cc410c90546ecf02c1c6cede7f66/src/mip-infinitescroll/mip-infinitescroll.js#L114-L115>

**Comment by xuexb** [comment]
感觉传个 `template="myTemplate"` 还不如直接查找组件内 `<template>` 标签语义化，（虽然说核心偌里的 `templates.js` 已经支持这个。

**Comment by xuexb** [comment]
![image](https://user-images.githubusercontent.com/3872051/34357623-962f412e-ea83-11e7-82bc-59e54dd8505a.png)

```html
<script type="application/json">
{
    "rn": 40,
    "pn": 1,
    "prn": 6,
    "pnName": "pn",
    "bufferHeightPx": 40,
    "loadingHtml": "正在加载...",
    "loadFailHtml": "加载失败~",
    "loadOverHtml": "没有数据了~"
}
</script>
```

我接口都报错报到老家了，页面居然还是加载中。

**Comment by jennyliang220** [comment]
问题有些多，一个一个回复：

1. mip-infinitescroll异步请求目前只支持 JSONP，[mip-infinitescroll文档](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html)中确实解释模糊，仅提到`异步请求数据接口（通过 JSONP 请求） `，我在文档中强调说明下。
2. [mip-list组件](https://www.mipengine.org/examples/mip-extensions/mip-list.html)配置写在属性中（而不是json中），确实与[mip-infinitescroll](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html)使用方式不同，有点别扭。但是：
    -  [mip-list组件](https://www.mipengine.org/examples/mip-extensions/mip-list.html)的json配置被[渲染同步数据](https://www.mipengine.org/examples/mip-extensions/mip-list.html#markdown-doc-%E5%90%8C%E6%AD%A5%E6%95%B0%E6%8D%AE)占用了
    - 这种通过属性来配置的方式，在其他组件中也有使用，如[mip-appdl](https://www.mipengine.org/examples/mip-extensions/mip-appdl.html), 目前没有强制统一
    - 请 @wupengFEX 在组件重构中看下，是否需要统一使用json配置组件？
3. mip-infinitescroll-loading 这个class在[mip-infinitescroll组件](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html)代码中有获取，也需要文档说明，我补充下。
<https://github.com/mipengine/mip-extensions/blob/7153faf68906cc410c90546ecf02c1c6cede7f66/src/mip-infinitescroll/mip-infinitescroll.js#L114-L115>
4. `template="myTemplate"`和`id="myTemplate" `理论上可以不写，在[template.js#L96-L100](https://github.com/mipengine/mip/blob/cf532ad5867bd8eba4fe3fe3de61aba9f8aa4869/src/templates.js#L96-L100)中有做兼容。我测试几个网站，如果效果OK，就改文档:.
5. [mip-infinitescroll组件](https://www.mipengine.org/examples/mip-extensions/mip-infinitescroll.html)源码中确实没有显示loadFailHtml 的逻辑，需要修改组件代码。
    - 表现为[代码](https://github.com/mipengine/mip-extensions/blob/7153faf68906cc410c90546ecf02c1c6cede7f66/src/mip-infinitescroll/mip-infinitescroll.js#L81)中全是`resolve`,
 没有`reject` , 在infinitescoll代码中只有遇到reject才会执行请求失败逻辑，显示loadFailHtml:
<https://github.com/mipengine/mip-extensions/blob/7153faf68906cc410c90546ecf02c1c6cede7f66/src/mip-infinitescroll/infinitescroll.js#L260-L271>.
