### ISSUE TITLE
on="tap"和百度统计事件追踪的click事件冲突

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/mip-extensions#986]
## 问题分类
MIP 组件使用

## 问题描述
```
<div 
    on="tap:lightbox.toggle"
    data-stats-baidu-obj="%7B%22type%22%3A%22click%22%2C%22data%22%3A%22%5B_trackPageview%2C%20%2Fmip-stats%2Fsheji%5D%22%7D">
    点击发送请求，打开弹框
</div>
```
on属性的tap和百度统计事件追踪的click事件冲突，on:tap时lightbox已经弹出，不会触发click事件。

## 复现方式（线上bug 填写此项）
页面URL： https://jennyliang220.github.io/miptests/mip-stats-baidu/tap-on.html

在pc上访问，可以正常发送事件。在移动端访问不发送事件统计。

## 您的建议方案
百度统计click事件改成touchend？mouseup？

**Comment by momofan** [comment]
问题已定位，百度统计的时间追踪绑定在 click 事件上，而移动端 click 点击有200ms 的延迟，在这段时间内，tap 事件又把 lightbox 的 dom 和背景 mask 的 dom 展现出来。导致 click 点击的位置失效。解决方案产出中

**Comment by wupengFEX** [comment]
@momofan @jennyliang220 我觉得可以使用的方法有以下几种方法：
1. 将组件中 click 在移动端变成 touchend。该方式可以在 mip.js 提供一个公用方法，用于绑定事件，区别 pc 和移动端（pc端click，移动端touchend）；
2. 延迟弹层出现时间，并加动画作为过度（渐显渐隐）；
个人倾向于方法一

**Comment by xuexb** [comment]
我感觉应该有 `tap`、`click` 事件，使用哪个取决于开发者，并且说明好 `tap` 事件延迟的问题。而这里就需要使用 `click` 事件。

我遇到的场景是使用 `tap` 事件调弹出层，弹出层里有链接，导致点击穿透，跳转页面。

**Comment by jennyliang220** [comment]
> wupengFEX: 延迟弹层出现时间，并加动画作为过度（渐显渐隐)

延迟200ms就可以解决问题，但不建议增加渐显渐隐。比如，200ms延迟+200ms动画，就显得更慢了。

除此之外的解决方案：
3. 在核心代码手势中，当tap触发时，手动trigger click事件。
https://github.com/mipengine/mip/blob/master/src/utils/gesture.js#L15-L22

**Comment by jennyliang220** [comment]
@momofan 提出，
1. 有交互有展现的事件，开发时使用click。
2. 所有绑定了tap事件的函数，click变成touchend。

**Comment by jennyliang220** [comment]
## 最终结论
### 快速解决
在百度统计（以及其它统计组件）中，绑定click时，判断此dom是否有on属性。如果有，click变成touchend。 @我
### 最终解决
参考 fastclick 方案，截获click事件。所有绑定click事件的元素，采用核心代码tap逻辑。 @xuexb

**Comment by jennyliang220** [comment]
#999 修复这个问题，2018.1.18已上线。上线后支持这样触发：

```
<button id="btn-open" on="tap:my-lightbox.open" data-stats-baidu-obj="%7B%22type%22%3A%22click%22%2C%22data%22%3A%22%5B_trackPageview%2C%20%2Fmip-stats%2Fsheji%5D%22%7D">
    点击打开弹层，触发统计 mip-stats%2Fsheji
</button>

<mip-lightbox
	id="my-lightbox"
	layout="nodisplay"
	autoclosetime="2"
	class="mip-hidden"
	content-scroll>
	<div class="lightbox">
		<h1>Hello, World!</h1>
		<span on="tap:my-lightbox.toggle" class="lightbox-close">关闭弹层</span>
	</div>
</mip-lightbox>
```
