### ISSUE TITLE
sidebar与fixed同时使用时，sidevar无法覆盖页面上的fixed

### ISSUE THREAD

**Issue by Tomqing** [mipengine/mip-extensions#991]
## 问题分类

（请在括号中输入"x"来选择）
- [x] MIP 组件使用
- [ ] MIP 页面内容（广告不显示，排版错乱）
- [ ] MIP 页面不通过校验
- [ ] MIP-Cache下效果异常

## 问题描述
sidebar与fixed同时使用时，sidevar无法覆盖页面上的fixed，不管是show出sidebar的按钮，还是页面上存在的fixed，层级都比sidebar高

## 复现方式（线上bug 填写此项）
1. 手机型号：
2. 系统版本：
3. 浏览器及版本：
4. 页面URL：http://www.enjoynode.com/test/mip-sidebar-test.html
5. 复现操作：

## 需求描述（新需求 填写此项）
1. 效果页面URL： 
2. 效果描述:

**Comment by Tomqing** [comment]
![qq 20180108142417](https://user-images.githubusercontent.com/8638696/34660799-24998fcc-f480-11e7-84c1-09777b6784af.png)

**Comment by Tomqing** [comment]
![qq 20180108142417](https://user-images.githubusercontent.com/8638696/34660799-24998fcc-f480-11e7-84c1-09777b6784af.png)

**Comment by wupengFEX** [comment]
目前 mip-fixed 的 z-index 是高于 sidebar 的，如果需要根据自己的需求来定义层级，可以在自定义 css 里面给元素加入更高层级。
