### ISSUE TITLE
mip-img 组件文档说明和效验规则不一致

### ISSUE THREAD

**Issue by gom3250** [mipengine/mip-extensions#996]
## 问题分类

（请在括号中输入"x"来选择）
- [x ] MIP 组件说明文档

## 问题描述
[地址](https://www.mipengine.org/examples/mip/mip-img.html)
说明文档中
width属性和height属性均为  必选项：是
但是在实际使用中不是必选项，不填也可以通过效验

## 您的建议方案
希望两边能够统一。减少大家误解

**Comment by wupengFEX** [comment]
[#265](https://github.com/mipengine/mip/pull/265)

**Comment by wupengFEX** [comment]
@gom3250 [文档](https://www.mipengine.org/examples/mip/mip-img.html) 已上线
